-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1532_26 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    img_full_n : IN STD_LOGIC;
    img_write : OUT STD_LOGIC;
    img_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    bytePlanes_plane0_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    bytePlanes_plane0_empty_n : IN STD_LOGIC;
    bytePlanes_plane0_read : OUT STD_LOGIC;
    bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    loopWidth_8 : IN STD_LOGIC_VECTOR (10 downto 0);
    icmp_ln1522 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln1548_5 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln1548_4 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln1548_3 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp48 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln1548_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln1548 : IN STD_LOGIC_VECTOR (11 downto 0);
    icmp45 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1532_26 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv16_8080 : STD_LOGIC_VECTOR (15 downto 0) := "1000000010000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal or_ln1548_6_reg_398 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_block_state9_pp0_stage0_iter1_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1532_fu_169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal icmp_ln1532_reg_370 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal or_ln1548_5_reg_394 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_predicate_op79_write_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage7_iter0_grp7 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal bytePlanes_plane0_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp1 : BOOLEAN;
    signal img_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp2 : BOOLEAN;
    signal or_ln1548_reg_374 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_grp3 : BOOLEAN;
    signal or_ln1548_1_reg_378 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_grp4 : BOOLEAN;
    signal or_ln1548_2_reg_382 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_grp5 : BOOLEAN;
    signal or_ln1548_3_reg_386 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_grp6 : BOOLEAN;
    signal or_ln1548_4_reg_390 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_block_pp0_stage7_grp7 : BOOLEAN;
    signal ap_block_pp0_stage0_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln1548_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1548_1_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1548_2_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1548_3_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1548_4_fu_215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1548_5_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1548_6_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_402 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_state2_pp0_stage1_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp1 : BOOLEAN;
    signal tmp_23_reg_407 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tmp_47_reg_412 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tmp_s_reg_417 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tmp_58_reg_422 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tmp_59_reg_427 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tmp_60_reg_432 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal x_fu_90 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal x_9_fu_175_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_8 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal or_ln1549_2_fu_242_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage1_01001_grp1 : BOOLEAN;
    signal or_ln1549_5_fu_307_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_predicate_op64_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage2_01001_grp2 : BOOLEAN;
    signal or_ln1549_8_fu_315_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_predicate_op67_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage3_01001_grp3 : BOOLEAN;
    signal or_ln1549_s_fu_323_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_predicate_op70_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0_grp4 : BOOLEAN;
    signal ap_block_pp0_stage4_01001_grp4 : BOOLEAN;
    signal or_ln1549_7_fu_331_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_predicate_op73_write_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage5_iter0_grp5 : BOOLEAN;
    signal ap_block_pp0_stage5_01001_grp5 : BOOLEAN;
    signal or_ln1549_1_fu_339_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_predicate_op76_write_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage6_iter0_grp6 : BOOLEAN;
    signal ap_block_pp0_stage6_01001_grp6 : BOOLEAN;
    signal or_ln1549_3_fu_347_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage7_01001_grp7 : BOOLEAN;
    signal or_ln1549_4_fu_355_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_01001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage3_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage4_11001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage5_11001_grp5 : BOOLEAN;
    signal ap_block_pp0_stage6_11001_grp6 : BOOLEAN;
    signal ap_block_pp0_stage7_11001_grp7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp8 : BOOLEAN;
    signal zext_ln1534_fu_181_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln1548_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1544_fu_238_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_frmbuf_rd_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component design_1_v_frmbuf_rd_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln1532_reg_370_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln1532_reg_370 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    icmp_ln1532_reg_370 <= icmp_ln1532_fu_169_p2;
                end if; 
            end if;
        end if;
    end process;


    or_ln1548_1_reg_378_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                or_ln1548_1_reg_378 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    or_ln1548_1_reg_378 <= or_ln1548_1_fu_197_p2;
                end if; 
            end if;
        end if;
    end process;


    or_ln1548_2_reg_382_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                or_ln1548_2_reg_382 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    or_ln1548_2_reg_382 <= or_ln1548_2_fu_203_p2;
                end if; 
            end if;
        end if;
    end process;


    or_ln1548_3_reg_386_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                or_ln1548_3_reg_386 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    or_ln1548_3_reg_386 <= or_ln1548_3_fu_209_p2;
                end if; 
            end if;
        end if;
    end process;


    or_ln1548_4_reg_390_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                or_ln1548_4_reg_390 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    or_ln1548_4_reg_390 <= or_ln1548_4_fu_215_p2;
                end if; 
            end if;
        end if;
    end process;


    or_ln1548_5_reg_394_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                or_ln1548_5_reg_394 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    or_ln1548_5_reg_394 <= or_ln1548_5_fu_221_p2;
                end if; 
            end if;
        end if;
    end process;


    or_ln1548_6_reg_398_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                or_ln1548_6_reg_398 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    or_ln1548_6_reg_398 <= or_ln1548_6_fu_227_p2;
                end if; 
            end if;
        end if;
    end process;


    or_ln1548_reg_374_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                or_ln1548_reg_374 <= ap_const_lv1_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    or_ln1548_reg_374 <= or_ln1548_fu_191_p2;
                end if; 
            end if;
        end if;
    end process;


    tmp_10_reg_402_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_10_reg_402 <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    tmp_10_reg_402 <= bytePlanes_plane0_dout(15 downto 8);
                end if; 
            end if;
        end if;
    end process;


    tmp_23_reg_407_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_23_reg_407 <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    tmp_23_reg_407 <= bytePlanes_plane0_dout(23 downto 16);
                end if; 
            end if;
        end if;
    end process;


    tmp_47_reg_412_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_47_reg_412 <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    tmp_47_reg_412 <= bytePlanes_plane0_dout(31 downto 24);
                end if; 
            end if;
        end if;
    end process;


    tmp_58_reg_422_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_58_reg_422 <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    tmp_58_reg_422 <= bytePlanes_plane0_dout(47 downto 40);
                end if; 
            end if;
        end if;
    end process;


    tmp_59_reg_427_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_59_reg_427 <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    tmp_59_reg_427 <= bytePlanes_plane0_dout(55 downto 48);
                end if; 
            end if;
        end if;
    end process;


    tmp_60_reg_432_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_60_reg_432 <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    tmp_60_reg_432 <= bytePlanes_plane0_dout(63 downto 56);
                end if; 
            end if;
        end if;
    end process;


    tmp_s_reg_417_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_s_reg_417 <= ap_const_lv8_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    tmp_s_reg_417 <= bytePlanes_plane0_dout(39 downto 32);
                end if; 
            end if;
        end if;
    end process;


    x_fu_90_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                x_fu_90 <= ap_const_lv11_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    if (((icmp_ln1532_fu_169_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                        x_fu_90 <= x_9_fu_175_p2;
                    elsif ((ap_loop_init = ap_const_logic_1)) then 
                        x_fu_90 <= ap_const_lv11_0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage7_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp8_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state9_pp0_stage0_iter1_grp8)
    begin
                ap_block_pp0_stage0_01001_grp8 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter1_grp8));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state9_pp0_stage0_iter1_grp8)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter1_grp8));
    end process;


    ap_block_pp0_stage0_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state9_pp0_stage0_iter1_grp8)
    begin
                ap_block_pp0_stage0_11001_grp8 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter1_grp8));
    end process;

        ap_block_pp0_stage0_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state9_pp0_stage0_iter1_grp8)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter1_grp8));
    end process;


    ap_block_pp0_stage1_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_01001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1));
    end process;


    ap_block_pp0_stage1_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_11001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1));
    end process;

        ap_block_pp0_stage1_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state2_pp0_stage1_iter0_grp1)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0_grp1));
    end process;


    ap_block_pp0_stage2_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp2)
    begin
                ap_block_pp0_stage2_01001_grp2 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp2));
    end process;


    ap_block_pp0_stage2_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp2)
    begin
                ap_block_pp0_stage2_11001_grp2 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp2));
    end process;

        ap_block_pp0_stage2_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state3_pp0_stage2_iter0_grp2)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0_grp2));
    end process;


    ap_block_pp0_stage3_01001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_01001_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3));
    end process;


    ap_block_pp0_stage3_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_11001_grp3 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3));
    end process;

        ap_block_pp0_stage3_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage3_iter0_grp3)
    begin
                ap_block_pp0_stage3_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage3_iter0_grp3));
    end process;


    ap_block_pp0_stage4_01001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp4)
    begin
                ap_block_pp0_stage4_01001_grp4 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp4));
    end process;


    ap_block_pp0_stage4_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp4)
    begin
                ap_block_pp0_stage4_11001_grp4 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp4));
    end process;

        ap_block_pp0_stage4_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_pp0_stage4_iter0_grp4)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp4));
    end process;


    ap_block_pp0_stage5_01001_grp5_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp5)
    begin
                ap_block_pp0_stage5_01001_grp5 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp5));
    end process;


    ap_block_pp0_stage5_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp5)
    begin
                ap_block_pp0_stage5_11001_grp5 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp5));
    end process;

        ap_block_pp0_stage5_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state6_pp0_stage5_iter0_grp5)
    begin
                ap_block_pp0_stage5_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage5_iter0_grp5));
    end process;


    ap_block_pp0_stage6_01001_grp6_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp6)
    begin
                ap_block_pp0_stage6_01001_grp6 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp6));
    end process;


    ap_block_pp0_stage6_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp6)
    begin
                ap_block_pp0_stage6_11001_grp6 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp6));
    end process;

        ap_block_pp0_stage6_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state7_pp0_stage6_iter0_grp6)
    begin
                ap_block_pp0_stage6_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage6_iter0_grp6));
    end process;


    ap_block_pp0_stage7_01001_grp7_assign_proc : process(ap_block_state8_pp0_stage7_iter0_grp7, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage7_01001_grp7 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp7));
    end process;


    ap_block_pp0_stage7_11001_grp7_assign_proc : process(ap_block_state8_pp0_stage7_iter0_grp7, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage7_11001_grp7 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp7));
    end process;

        ap_block_pp0_stage7_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_subdone_assign_proc : process(ap_block_state8_pp0_stage7_iter0_grp7, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage7_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage7_iter0_grp7));
    end process;


    ap_block_state2_pp0_stage1_iter0_grp1_assign_proc : process(img_full_n, bytePlanes_plane0_empty_n, icmp_ln1532_reg_370)
    begin
                ap_block_state2_pp0_stage1_iter0_grp1 <= (((icmp_ln1532_reg_370 = ap_const_lv1_0) and (img_full_n = ap_const_logic_0)) or ((icmp_ln1532_reg_370 = ap_const_lv1_0) and (bytePlanes_plane0_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state3_pp0_stage2_iter0_grp2_assign_proc : process(img_full_n, ap_predicate_op64_write_state3)
    begin
                ap_block_state3_pp0_stage2_iter0_grp2 <= ((img_full_n = ap_const_logic_0) and (ap_predicate_op64_write_state3 = ap_const_boolean_1));
    end process;


    ap_block_state4_pp0_stage3_iter0_grp3_assign_proc : process(img_full_n, ap_predicate_op67_write_state4)
    begin
                ap_block_state4_pp0_stage3_iter0_grp3 <= ((img_full_n = ap_const_logic_0) and (ap_predicate_op67_write_state4 = ap_const_boolean_1));
    end process;


    ap_block_state5_pp0_stage4_iter0_grp4_assign_proc : process(img_full_n, ap_predicate_op70_write_state5)
    begin
                ap_block_state5_pp0_stage4_iter0_grp4 <= ((img_full_n = ap_const_logic_0) and (ap_predicate_op70_write_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp0_stage5_iter0_grp5_assign_proc : process(img_full_n, ap_predicate_op73_write_state6)
    begin
                ap_block_state6_pp0_stage5_iter0_grp5 <= ((img_full_n = ap_const_logic_0) and (ap_predicate_op73_write_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_pp0_stage6_iter0_grp6_assign_proc : process(img_full_n, ap_predicate_op76_write_state7)
    begin
                ap_block_state7_pp0_stage6_iter0_grp6 <= ((img_full_n = ap_const_logic_0) and (ap_predicate_op76_write_state7 = ap_const_boolean_1));
    end process;


    ap_block_state8_pp0_stage7_iter0_grp7_assign_proc : process(img_full_n, ap_predicate_op79_write_state8)
    begin
                ap_block_state8_pp0_stage7_iter0_grp7 <= ((ap_predicate_op79_write_state8 = ap_const_boolean_1) and (img_full_n = ap_const_logic_0));
    end process;


    ap_block_state9_pp0_stage0_iter1_grp8_assign_proc : process(img_full_n, or_ln1548_6_reg_398)
    begin
                ap_block_state9_pp0_stage0_iter1_grp8 <= ((or_ln1548_6_reg_398 = ap_const_lv1_1) and (img_full_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1532_fu_169_p2)
    begin
        if (((icmp_ln1532_fu_169_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op64_write_state3_assign_proc : process(icmp_ln1532_reg_370, or_ln1548_reg_374)
    begin
                ap_predicate_op64_write_state3 <= ((icmp_ln1532_reg_370 = ap_const_lv1_0) and (or_ln1548_reg_374 = ap_const_lv1_1));
    end process;


    ap_predicate_op67_write_state4_assign_proc : process(icmp_ln1532_reg_370, or_ln1548_1_reg_378)
    begin
                ap_predicate_op67_write_state4 <= ((icmp_ln1532_reg_370 = ap_const_lv1_0) and (or_ln1548_1_reg_378 = ap_const_lv1_1));
    end process;


    ap_predicate_op70_write_state5_assign_proc : process(icmp_ln1532_reg_370, or_ln1548_2_reg_382)
    begin
                ap_predicate_op70_write_state5 <= ((icmp_ln1532_reg_370 = ap_const_lv1_0) and (or_ln1548_2_reg_382 = ap_const_lv1_1));
    end process;


    ap_predicate_op73_write_state6_assign_proc : process(icmp_ln1532_reg_370, or_ln1548_3_reg_386)
    begin
                ap_predicate_op73_write_state6 <= ((icmp_ln1532_reg_370 = ap_const_lv1_0) and (or_ln1548_3_reg_386 = ap_const_lv1_1));
    end process;


    ap_predicate_op76_write_state7_assign_proc : process(icmp_ln1532_reg_370, or_ln1548_4_reg_390)
    begin
                ap_predicate_op76_write_state7 <= ((icmp_ln1532_reg_370 = ap_const_lv1_0) and (or_ln1548_4_reg_390 = ap_const_lv1_1));
    end process;


    ap_predicate_op79_write_state8_assign_proc : process(icmp_ln1532_reg_370, or_ln1548_5_reg_394)
    begin
                ap_predicate_op79_write_state8 <= ((or_ln1548_5_reg_394 = ap_const_lv1_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage7, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage7_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_8_assign_proc : process(ap_CS_fsm_pp0_stage0, x_fu_90, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_8 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_x_8 <= x_fu_90;
        end if; 
    end process;


    bytePlanes_plane0_blk_n_assign_proc : process(bytePlanes_plane0_empty_n, icmp_ln1532_reg_370, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane0_blk_n <= bytePlanes_plane0_empty_n;
        else 
            bytePlanes_plane0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bytePlanes_plane0_read_assign_proc : process(icmp_ln1532_reg_370, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane0_read <= ap_const_logic_1;
        else 
            bytePlanes_plane0_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1532_fu_169_p2 <= "1" when (ap_sig_allocacmp_x_8 = loopWidth_8) else "0";
    icmp_ln1548_fu_185_p2 <= "1" when (signed(zext_ln1534_fu_181_p1) < signed(sext_ln1548)) else "0";

    img_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, img_full_n, or_ln1548_6_reg_398, ap_CS_fsm_pp0_stage7, icmp_ln1532_reg_370, ap_predicate_op79_write_state8, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp2, or_ln1548_reg_374, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_grp3, or_ln1548_1_reg_378, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_grp4, or_ln1548_2_reg_382, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_grp5, or_ln1548_3_reg_386, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_grp6, or_ln1548_4_reg_390, ap_block_pp0_stage7_grp7, ap_block_pp0_stage0_grp8)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_predicate_op79_write_state8 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage6_grp6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (or_ln1548_4_reg_390 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage5_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (or_ln1548_3_reg_386 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (or_ln1548_2_reg_382 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 
    = ap_block_pp0_stage3_grp3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (or_ln1548_1_reg_378 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln1548_reg_374 = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_grp8) and (or_ln1548_6_reg_398 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            img_blk_n <= img_full_n;
        else 
            img_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_din_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_ln1548_6_reg_398, ap_CS_fsm_pp0_stage7, icmp_ln1532_reg_370, ap_predicate_op79_write_state8, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, or_ln1549_2_fu_242_p3, ap_block_pp0_stage1_01001_grp1, or_ln1549_5_fu_307_p3, ap_predicate_op64_write_state3, ap_block_pp0_stage2_01001_grp2, or_ln1549_8_fu_315_p3, ap_predicate_op67_write_state4, ap_block_pp0_stage3_01001_grp3, or_ln1549_s_fu_323_p3, ap_predicate_op70_write_state5, ap_block_pp0_stage4_01001_grp4, or_ln1549_7_fu_331_p3, ap_predicate_op73_write_state6, ap_block_pp0_stage5_01001_grp5, or_ln1549_1_fu_339_p3, ap_predicate_op76_write_state7, ap_block_pp0_stage6_01001_grp6, or_ln1549_3_fu_347_p3, ap_block_pp0_stage7_01001_grp7, or_ln1549_4_fu_355_p3, ap_block_pp0_stage0_01001_grp8)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp8) and (or_ln1548_6_reg_398 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_din <= or_ln1549_4_fu_355_p3;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_predicate_op79_write_state8 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_01001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            img_din <= or_ln1549_3_fu_347_p3;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_01001_grp6) and (ap_predicate_op76_write_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            img_din <= or_ln1549_1_fu_339_p3;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_01001_grp5) and (ap_predicate_op73_write_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            img_din <= or_ln1549_7_fu_331_p3;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_01001_grp4) and (ap_predicate_op70_write_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            img_din <= or_ln1549_s_fu_323_p3;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_01001_grp3) and (ap_predicate_op67_write_state4 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            img_din <= or_ln1549_8_fu_315_p3;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_01001_grp2) and (ap_predicate_op64_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            img_din <= or_ln1549_5_fu_307_p3;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            img_din <= or_ln1549_2_fu_242_p3;
        else 
            img_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    img_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_ln1548_6_reg_398, ap_CS_fsm_pp0_stage7, icmp_ln1532_reg_370, ap_predicate_op79_write_state8, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage1_11001_grp1, ap_predicate_op64_write_state3, ap_predicate_op67_write_state4, ap_predicate_op70_write_state5, ap_predicate_op73_write_state6, ap_predicate_op76_write_state7, ap_block_pp0_stage2_11001_grp2, ap_block_pp0_stage3_11001_grp3, ap_block_pp0_stage4_11001_grp4, ap_block_pp0_stage5_11001_grp5, ap_block_pp0_stage6_11001_grp6, ap_block_pp0_stage7_11001_grp7, ap_block_pp0_stage0_11001_grp8)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_predicate_op79_write_state8 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001_grp7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (icmp_ln1532_reg_370 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage6_11001_grp6) and (ap_predicate_op76_write_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001_grp5) and (ap_predicate_op73_write_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp4) and (ap_predicate_op70_write_state5 = ap_const_boolean_1) and (ap_const_logic_1 
    = ap_CS_fsm_pp0_stage4)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001_grp3) and (ap_predicate_op67_write_state4 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp2) and (ap_predicate_op64_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp8) and (or_ln1548_6_reg_398 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            img_write <= ap_const_logic_1;
        else 
            img_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln1548_1_fu_197_p2 <= (icmp_ln1548_fu_185_p2 or icmp_ln1548_1);
    or_ln1548_2_fu_203_p2 <= (icmp_ln1548_fu_185_p2 or icmp48);
    or_ln1548_3_fu_209_p2 <= (icmp_ln1548_fu_185_p2 or icmp_ln1548_3);
    or_ln1548_4_fu_215_p2 <= (icmp_ln1548_fu_185_p2 or icmp_ln1548_4);
    or_ln1548_5_fu_221_p2 <= (icmp_ln1548_fu_185_p2 or icmp_ln1548_5);
    or_ln1548_6_fu_227_p2 <= (icmp_ln1548_fu_185_p2 or icmp_ln1522);
    or_ln1548_fu_191_p2 <= (icmp_ln1548_fu_185_p2 or icmp45);
    or_ln1549_1_fu_339_p3 <= (ap_const_lv16_8080 & tmp_58_reg_422);
    or_ln1549_2_fu_242_p3 <= (ap_const_lv16_8080 & trunc_ln1544_fu_238_p1);
    or_ln1549_3_fu_347_p3 <= (ap_const_lv16_8080 & tmp_59_reg_427);
    or_ln1549_4_fu_355_p3 <= (ap_const_lv16_8080 & tmp_60_reg_432);
    or_ln1549_5_fu_307_p3 <= (ap_const_lv16_8080 & tmp_10_reg_402);
    or_ln1549_7_fu_331_p3 <= (ap_const_lv16_8080 & tmp_s_reg_417);
    or_ln1549_8_fu_315_p3 <= (ap_const_lv16_8080 & tmp_23_reg_407);
    or_ln1549_s_fu_323_p3 <= (ap_const_lv16_8080 & tmp_47_reg_412);
    trunc_ln1544_fu_238_p1 <= bytePlanes_plane0_dout(8 - 1 downto 0);
    x_9_fu_175_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_8) + unsigned(ap_const_lv11_1));
    zext_ln1534_fu_181_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x_8),12));
end behav;
