-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_design_v_mix_0_0_v_mix_core_alpha_false_false_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    outLayer0_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    outLayer0_empty_n : IN STD_LOGIC;
    outLayer0_read : OUT STD_LOGIC;
    outLayer0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    outLayer0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1x_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    srcLayer1x_empty_n : IN STD_LOGIC;
    srcLayer1x_read : OUT STD_LOGIC;
    srcLayer1x_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1x_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    hwReg_width_val : IN STD_LOGIC_VECTOR (10 downto 0);
    hwReg_height_val : IN STD_LOGIC_VECTOR (10 downto 0);
    hwReg_background_Y_R_val : IN STD_LOGIC_VECTOR (7 downto 0);
    hwReg_background_U_G_val : IN STD_LOGIC_VECTOR (7 downto 0);
    hwReg_background_V_B_val : IN STD_LOGIC_VECTOR (7 downto 0);
    hwReg_layerEnable_val : IN STD_LOGIC_VECTOR (1 downto 0);
    hwReg_layerStartX_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    hwReg_layerStartY_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    hwReg_layerWidth_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    hwReg_layerHeight_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    hwReg_layerScaleFactor_1_val : IN STD_LOGIC_VECTOR (7 downto 0);
    outLayer1_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    outLayer1_full_n : IN STD_LOGIC;
    outLayer1_write : OUT STD_LOGIC;
    outLayer1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    outLayer1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of top_design_v_mix_0_0_v_mix_core_alpha_false_false_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal hwReg_layerStartY_1_val_read_reg_281 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal hwReg_layerStartX_1_val_read_reg_286 : STD_LOGIC_VECTOR (15 downto 0);
    signal hwReg_background_V_B_val_read_reg_291 : STD_LOGIC_VECTOR (7 downto 0);
    signal hwReg_background_U_G_val_read_reg_296 : STD_LOGIC_VECTOR (7 downto 0);
    signal hwReg_background_Y_R_val_read_reg_301 : STD_LOGIC_VECTOR (7 downto 0);
    signal hwReg_height_val_read_reg_306 : STD_LOGIC_VECTOR (10 downto 0);
    signal hwReg_width_val_read_reg_311 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_fu_166_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_316 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln476_fu_198_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln476_reg_321 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln478_fu_212_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln478_reg_326 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_5_reg_331 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln476_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln476_reg_339 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln476_1_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln476_1_reg_344 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln476_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln476_reg_349 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_start : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_done : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_idle : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_ready : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_outLayer0_read : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_srcLayer1x_read : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_outLayer1_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_outLayer1_write : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal y_fu_76 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln463_fu_239_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln463_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hwReg_layerScaleFactor_1_val_readcast_fu_170_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal hwReg_layerScaleFactor_1_val_readcast23_fu_180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln449_fu_174_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln476_1_fu_194_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln476_fu_190_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln450_fu_184_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln478_1_fu_208_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln478_fu_204_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln463_1_fu_249_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln463_fu_245_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_design_v_mix_0_0_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        outLayer0_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        outLayer0_empty_n : IN STD_LOGIC;
        outLayer0_read : OUT STD_LOGIC;
        outLayer0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        outLayer0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1x_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        srcLayer1x_empty_n : IN STD_LOGIC;
        srcLayer1x_read : OUT STD_LOGIC;
        srcLayer1x_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1x_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        outLayer1_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        outLayer1_full_n : IN STD_LOGIC;
        outLayer1_write : OUT STD_LOGIC;
        outLayer1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        outLayer1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        hwReg_width_val : IN STD_LOGIC_VECTOR (10 downto 0);
        hwReg_background_Y_R_val : IN STD_LOGIC_VECTOR (7 downto 0);
        hwReg_background_U_G_val : IN STD_LOGIC_VECTOR (7 downto 0);
        hwReg_background_V_B_val : IN STD_LOGIC_VECTOR (7 downto 0);
        hwReg_layerStartX_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
        add_ln478 : IN STD_LOGIC_VECTOR (16 downto 0);
        icmp_ln476_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        rev5 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_60 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146 : component top_design_v_mix_0_0_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_start,
        ap_done => grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_done,
        ap_idle => grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_idle,
        ap_ready => grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_ready,
        outLayer0_dout => outLayer0_dout,
        outLayer0_empty_n => outLayer0_empty_n,
        outLayer0_read => grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_outLayer0_read,
        outLayer0_num_data_valid => ap_const_lv3_0,
        outLayer0_fifo_cap => ap_const_lv3_0,
        srcLayer1x_dout => srcLayer1x_dout,
        srcLayer1x_empty_n => srcLayer1x_empty_n,
        srcLayer1x_read => grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_srcLayer1x_read,
        srcLayer1x_num_data_valid => ap_const_lv3_0,
        srcLayer1x_fifo_cap => ap_const_lv3_0,
        outLayer1_din => grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_outLayer1_din,
        outLayer1_full_n => outLayer1_full_n,
        outLayer1_write => grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_outLayer1_write,
        outLayer1_num_data_valid => outLayer1_num_data_valid,
        outLayer1_fifo_cap => outLayer1_fifo_cap,
        hwReg_width_val => hwReg_width_val_read_reg_311,
        hwReg_background_Y_R_val => hwReg_background_Y_R_val_read_reg_301,
        hwReg_background_U_G_val => hwReg_background_U_G_val_read_reg_296,
        hwReg_background_V_B_val => hwReg_background_V_B_val_read_reg_291,
        hwReg_layerStartX_1_val => hwReg_layerStartX_1_val_read_reg_286,
        add_ln478 => add_ln478_reg_326,
        icmp_ln476_1 => icmp_ln476_1_reg_344,
        rev5 => xor_ln476_reg_349,
        empty_60 => tmp_5_reg_331,
        empty => empty_reg_316);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_234_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_ready = ap_const_logic_1)) then 
                    grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_76 <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_234_p2 = ap_const_lv1_0))) then 
                y_fu_76 <= add_ln463_fu_239_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln476_reg_321 <= add_ln476_fu_198_p2;
                add_ln478_reg_326 <= add_ln478_fu_212_p2;
                empty_reg_316 <= empty_fu_166_p1;
                hwReg_background_U_G_val_read_reg_296 <= hwReg_background_U_G_val;
                hwReg_background_V_B_val_read_reg_291 <= hwReg_background_V_B_val;
                hwReg_background_Y_R_val_read_reg_301 <= hwReg_background_Y_R_val;
                hwReg_height_val_read_reg_306 <= hwReg_height_val;
                hwReg_layerStartX_1_val_read_reg_286 <= hwReg_layerStartX_1_val;
                hwReg_layerStartY_1_val_read_reg_281 <= hwReg_layerStartY_1_val;
                hwReg_width_val_read_reg_311 <= hwReg_width_val;
                tmp_5_reg_331 <= hwReg_layerEnable_val(1 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln476_1_reg_344 <= icmp_ln476_1_fu_258_p2;
                icmp_ln476_reg_339 <= icmp_ln476_fu_253_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                xor_ln476_reg_349 <= xor_ln476_fu_268_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_done, ap_CS_fsm_state4, icmp_ln463_fu_234_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_234_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln463_fu_239_p2 <= std_logic_vector(unsigned(y_fu_76) + unsigned(ap_const_lv11_1));
    add_ln476_fu_198_p2 <= std_logic_vector(unsigned(zext_ln476_1_fu_194_p1) + unsigned(zext_ln476_fu_190_p1));
    add_ln478_fu_212_p2 <= std_logic_vector(unsigned(zext_ln478_1_fu_208_p1) + unsigned(zext_ln478_fu_204_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_done)
    begin
        if ((grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln463_fu_234_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_234_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    empty_fu_166_p1 <= hwReg_layerEnable_val(1 - 1 downto 0);
    grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_start <= grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_ap_start_reg;
    hwReg_layerScaleFactor_1_val_readcast23_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hwReg_layerScaleFactor_1_val),16));
    hwReg_layerScaleFactor_1_val_readcast_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hwReg_layerScaleFactor_1_val),16));
    icmp_ln463_fu_234_p2 <= "1" when (y_fu_76 = hwReg_height_val_read_reg_306) else "0";
    icmp_ln476_1_fu_258_p2 <= "1" when (unsigned(add_ln476_reg_321) > unsigned(zext_ln463_fu_245_p1)) else "0";
    icmp_ln476_fu_253_p2 <= "1" when (unsigned(zext_ln463_1_fu_249_p1) < unsigned(hwReg_layerStartY_1_val_read_reg_281)) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln463_fu_234_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_234_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    outLayer0_read <= grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_outLayer0_read;
    outLayer1_din <= grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_outLayer1_din;
    outLayer1_write <= grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_outLayer1_write;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    shl_ln449_fu_174_p2 <= std_logic_vector(shift_left(unsigned(hwReg_layerHeight_1_val),to_integer(unsigned('0' & hwReg_layerScaleFactor_1_val_readcast_fu_170_p1(16-1 downto 0)))));
    shl_ln450_fu_184_p2 <= std_logic_vector(shift_left(unsigned(hwReg_layerWidth_1_val),to_integer(unsigned('0' & hwReg_layerScaleFactor_1_val_readcast23_fu_180_p1(16-1 downto 0)))));
    srcLayer1x_read <= grp_v_mix_core_alpha_false_false_Pipeline_VITIS_LOOP_465_3_fu_146_srcLayer1x_read;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln476_fu_268_p2 <= (icmp_ln476_reg_339 xor ap_const_lv1_1);
    zext_ln463_1_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_76),16));
    zext_ln463_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_76),17));
    zext_ln476_1_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln449_fu_174_p2),17));
    zext_ln476_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hwReg_layerStartY_1_val),17));
    zext_ln478_1_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln450_fu_184_p2),17));
    zext_ln478_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hwReg_layerStartX_1_val),17));
end behav;
