// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_mix_0_0_v_mix_rgb2yuv_false_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        outLayer1_dout,
        outLayer1_empty_n,
        outLayer1_read,
        outLayer1_num_data_valid,
        outLayer1_fifo_cap,
        height_val,
        width_val,
        outYuv_din,
        outYuv_full_n,
        outYuv_write,
        outYuv_num_data_valid,
        outYuv_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] outLayer1_dout;
input   outLayer1_empty_n;
output   outLayer1_read;
input  [2:0] outLayer1_num_data_valid;
input  [2:0] outLayer1_fifo_cap;
input  [10:0] height_val;
input  [10:0] width_val;
output  [23:0] outYuv_din;
input   outYuv_full_n;
output   outYuv_write;
input  [31:0] outYuv_num_data_valid;
input  [31:0] outYuv_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [10:0] width_val_read_reg_101;
reg    ap_block_state1;
reg   [10:0] height_val_read_reg_106;
wire   [10:0] y_10_fu_84_p2;
reg   [10:0] y_10_reg_114;
wire    ap_CS_fsm_state2;
wire    grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_start;
wire    grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_done;
wire    grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_idle;
wire    grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_ready;
wire    grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_outLayer1_read;
wire   [23:0] grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_outYuv_din;
wire    grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_outYuv_write;
reg    grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_start_reg;
wire   [0:0] icmp_ln1040_fu_79_p2;
wire    ap_CS_fsm_state3;
reg   [10:0] y_fu_46;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_start_reg = 1'b0;
#0 y_fu_46 = 11'd0;
end

design_1_v_mix_0_0_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2 grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_start),
    .ap_done(grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_done),
    .ap_idle(grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_idle),
    .ap_ready(grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_ready),
    .outLayer1_dout(outLayer1_dout),
    .outLayer1_empty_n(outLayer1_empty_n),
    .outLayer1_read(grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_outLayer1_read),
    .outLayer1_num_data_valid(3'd0),
    .outLayer1_fifo_cap(3'd0),
    .outYuv_din(grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_outYuv_din),
    .outYuv_full_n(outYuv_full_n),
    .outYuv_write(grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_outYuv_write),
    .outYuv_num_data_valid(outYuv_num_data_valid),
    .outYuv_fifo_cap(outYuv_fifo_cap),
    .width_val(width_val_read_reg_101)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln1040_fu_79_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1040_fu_79_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_start_reg <= 1'b1;
        end else if ((grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_ready == 1'b1)) begin
            grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_46 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        y_fu_46 <= y_10_reg_114;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val_read_reg_106 <= height_val;
        width_val_read_reg_101 <= width_val;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_10_reg_114 <= y_10_fu_84_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1040_fu_79_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1040_fu_79_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln1040_fu_79_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_start = grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_ap_start_reg;

assign icmp_ln1040_fu_79_p2 = ((y_fu_46 == height_val_read_reg_106) ? 1'b1 : 1'b0);

assign outLayer1_read = grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_outLayer1_read;

assign outYuv_din = grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_outYuv_din;

assign outYuv_write = grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62_outYuv_write;

assign start_out = real_start;

assign y_10_fu_84_p2 = (y_fu_46 + 11'd1);

endmodule //design_1_v_mix_0_0_v_mix_rgb2yuv_false_s
