// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1197_14 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_din,
        img_full_n,
        img_write,
        img_num_data_valid,
        img_fifo_cap,
        bytePlanes_plane0_dout,
        bytePlanes_plane0_empty_n,
        bytePlanes_plane0_read,
        bytePlanes_plane0_num_data_valid,
        bytePlanes_plane0_fifo_cap,
        loopWidth_4,
        icmp_ln1187,
        icmp_ln1213_1,
        sext_ln1213,
        icmp29
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [23:0] img_din;
input   img_full_n;
output   img_write;
input  [31:0] img_num_data_valid;
input  [31:0] img_fifo_cap;
input  [63:0] bytePlanes_plane0_dout;
input   bytePlanes_plane0_empty_n;
output   bytePlanes_plane0_read;
input  [9:0] bytePlanes_plane0_num_data_valid;
input  [9:0] bytePlanes_plane0_fifo_cap;
input  [10:0] loopWidth_4;
input  [0:0] icmp_ln1187;
input  [0:0] icmp_ln1213_1;
input  [11:0] sext_ln1213;
input  [0:0] icmp29;

reg ap_idle;
reg[23:0] img_din;
reg img_write;
reg bytePlanes_plane0_read;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] or_ln1213_2_reg_321;
reg    ap_block_state5_pp0_stage0_iter1_grp4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1197_fu_145_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] icmp_ln1197_reg_309;
reg   [0:0] or_ln1213_1_reg_317;
reg    ap_predicate_op54_write_state4;
reg    ap_block_state4_pp0_stage3_iter0_grp3;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage3_subdone;
reg    bytePlanes_plane0_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg    img_blk_n;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp2;
reg   [0:0] or_ln1213_reg_313;
wire    ap_block_pp0_stage3_grp3;
wire    ap_block_pp0_stage0_grp4;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln1213_fu_167_p2;
wire   [0:0] or_ln1213_1_fu_173_p2;
wire   [0:0] or_ln1213_2_fu_179_p2;
reg   [7:0] tmp_7_reg_325;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
reg   [7:0] tmp_19_reg_330;
reg   [7:0] tmp_21_reg_335;
reg   [7:0] tmp_39_reg_340;
reg   [7:0] tmp_41_reg_345;
reg   [7:0] tmp_58_reg_350;
reg   [10:0] x_4_fu_90;
wire   [10:0] x_13_fu_151_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_x;
wire    ap_block_pp0_stage0;
wire   [23:0] zext_ln1214_fu_210_p1;
reg    ap_block_pp0_stage1_01001_grp1;
wire   [23:0] zext_ln1214_1_fu_275_p1;
reg    ap_predicate_op50_write_state3;
reg    ap_block_state3_pp0_stage2_iter0_grp2;
reg    ap_block_pp0_stage2_01001_grp2;
wire   [23:0] zext_ln1214_2_fu_286_p1;
reg    ap_block_pp0_stage3_01001_grp3;
wire   [23:0] zext_ln1214_3_fu_297_p1;
reg    ap_block_pp0_stage0_01001_grp4;
reg    ap_block_pp0_stage2_11001_grp2;
reg    ap_block_pp0_stage3_11001_grp3;
reg    ap_block_pp0_stage0_11001_grp4;
wire   [11:0] zext_ln1199_fu_157_p1;
wire   [0:0] icmp_ln1213_fu_161_p2;
wire   [7:0] trunc_ln1214_fu_198_p1;
wire   [7:0] tmp_3_fu_190_p3;
wire   [15:0] tmp_6_fu_202_p3;
wire   [15:0] tmp_20_fu_269_p3;
wire   [15:0] tmp_40_fu_280_p3;
wire   [15:0] tmp_59_fu_291_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 or_ln1213_2_reg_321 = 1'd0;
#0 icmp_ln1197_reg_309 = 1'd0;
#0 or_ln1213_1_reg_317 = 1'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 or_ln1213_reg_313 = 1'd0;
#0 tmp_7_reg_325 = 8'd0;
#0 tmp_19_reg_330 = 8'd0;
#0 tmp_21_reg_335 = 8'd0;
#0 tmp_39_reg_340 = 8'd0;
#0 tmp_41_reg_345 = 8'd0;
#0 tmp_58_reg_350 = 8'd0;
#0 x_4_fu_90 = 11'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_frmbuf_rd_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1197_reg_309 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            icmp_ln1197_reg_309 <= icmp_ln1197_fu_145_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln1213_1_reg_317 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln1213_1_reg_317 <= or_ln1213_1_fu_173_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln1213_2_reg_321 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln1213_2_reg_321 <= or_ln1213_2_fu_179_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        or_ln1213_reg_313 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            or_ln1213_reg_313 <= or_ln1213_fu_167_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_19_reg_330 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_19_reg_330 <= {{bytePlanes_plane0_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_21_reg_335 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_21_reg_335 <= {{bytePlanes_plane0_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_39_reg_340 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_39_reg_340 <= {{bytePlanes_plane0_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_41_reg_345 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_41_reg_345 <= {{bytePlanes_plane0_dout[63:56]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_58_reg_350 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_58_reg_350 <= {{bytePlanes_plane0_dout[55:48]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_7_reg_325 <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            tmp_7_reg_325 <= {{bytePlanes_plane0_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_4_fu_90 <= 11'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            if (((icmp_ln1197_fu_145_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                x_4_fu_90 <= x_13_fu_151_p2;
            end else if ((ap_loop_init == 1'b1)) begin
                x_4_fu_90 <= 11'd0;
            end
        end
    end
end

always @ (*) begin
    if (((icmp_ln1197_fu_145_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x = 11'd0;
    end else begin
        ap_sig_allocacmp_x = x_4_fu_90;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln1197_reg_309 == 1'd0) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane0_blk_n = bytePlanes_plane0_empty_n;
    end else begin
        bytePlanes_plane0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln1197_reg_309 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane0_read = 1'b1;
    end else begin
        bytePlanes_plane0_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op54_write_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp3) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln1197_reg_309 == 1'd0) & (1'b0 == ap_block_pp0_stage2_grp2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln1213_reg_313 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln1197_reg_309 == 1'd0) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_grp4) & (or_ln1213_2_reg_321 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_blk_n = img_full_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001_grp4) & (or_ln1213_2_reg_321 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_din = zext_ln1214_3_fu_297_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op54_write_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_01001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        img_din = zext_ln1214_2_fu_286_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_01001_grp2) & (ap_predicate_op50_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        img_din = zext_ln1214_1_fu_275_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln1197_reg_309 == 1'd0) & (1'b0 == ap_block_pp0_stage1_01001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_din = zext_ln1214_fu_210_p1;
    end else begin
        img_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_op54_write_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln1197_reg_309 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_predicate_op50_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001_grp4) & (or_ln1213_2_reg_321 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_write = 1'b1;
    end else begin
        img_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp4 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1_grp4));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1_grp4));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp4 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1_grp4));
end

assign ap_block_pp0_stage0_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1_grp4));
end

always @ (*) begin
    ap_block_pp0_stage1_01001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage2_01001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

always @ (*) begin
    ap_block_pp0_stage3_01001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

assign ap_block_pp0_stage3_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = (((icmp_ln1197_reg_309 == 1'd0) & (img_full_n == 1'b0)) | ((icmp_ln1197_reg_309 == 1'd0) & (bytePlanes_plane0_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp2 = ((img_full_n == 1'b0) & (ap_predicate_op50_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0_grp3 = ((ap_predicate_op54_write_state4 == 1'b1) & (img_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1_grp4 = ((or_ln1213_2_reg_321 == 1'd1) & (img_full_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op50_write_state3 = ((icmp_ln1197_reg_309 == 1'd0) & (or_ln1213_reg_313 == 1'd1));
end

always @ (*) begin
    ap_predicate_op54_write_state4 = ((or_ln1213_1_reg_317 == 1'd1) & (icmp_ln1197_reg_309 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign icmp_ln1197_fu_145_p2 = ((ap_sig_allocacmp_x == loopWidth_4) ? 1'b1 : 1'b0);

assign icmp_ln1213_fu_161_p2 = (($signed(zext_ln1199_fu_157_p1) < $signed(sext_ln1213)) ? 1'b1 : 1'b0);

assign or_ln1213_1_fu_173_p2 = (icmp_ln1213_fu_161_p2 | icmp_ln1213_1);

assign or_ln1213_2_fu_179_p2 = (icmp_ln1213_fu_161_p2 | icmp_ln1187);

assign or_ln1213_fu_167_p2 = (icmp_ln1213_fu_161_p2 | icmp29);

assign tmp_20_fu_269_p3 = {{tmp_19_reg_330}, {tmp_7_reg_325}};

assign tmp_3_fu_190_p3 = {{bytePlanes_plane0_dout[15:8]}};

assign tmp_40_fu_280_p3 = {{tmp_39_reg_340}, {tmp_21_reg_335}};

assign tmp_59_fu_291_p3 = {{tmp_58_reg_350}, {tmp_41_reg_345}};

assign tmp_6_fu_202_p3 = {{trunc_ln1214_fu_198_p1}, {tmp_3_fu_190_p3}};

assign trunc_ln1214_fu_198_p1 = bytePlanes_plane0_dout[7:0];

assign x_13_fu_151_p2 = (ap_sig_allocacmp_x + 11'd1);

assign zext_ln1199_fu_157_p1 = ap_sig_allocacmp_x;

assign zext_ln1214_1_fu_275_p1 = tmp_20_fu_269_p3;

assign zext_ln1214_2_fu_286_p1 = tmp_40_fu_280_p3;

assign zext_ln1214_3_fu_297_p1 = tmp_59_fu_291_p3;

assign zext_ln1214_fu_210_p1 = tmp_6_fu_202_p3;

endmodule //design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1197_14
