# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.srcs/sources_1/bd/top_design/ip/top_design_axi_smc_1/top_design_axi_smc_1.xci
# IP: The module: 'top_design_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/bd_b6ca.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_1/bd_b6ca_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_2/bd_b6ca_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_3/bd_b6ca_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_4/bd_b6ca_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_5/bd_b6ca_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_6/bd_b6ca_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_7/bd_b6ca_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_8/bd_b6ca_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_9/bd_b6ca_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_1/bd_b6ca_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_5/bd_b6ca_s00a2s_0_ooc.xdc

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_6/bd_b6ca_sarn_0_ooc.xdc

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_7/bd_b6ca_srn_0_ooc.xdc

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_8/bd_b6ca_m00s2a_0_ooc.xdc

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_design_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_design_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.srcs/sources_1/bd/top_design/ip/top_design_axi_smc_1/top_design_axi_smc_1.xci
# IP: The module: 'top_design_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/bd_b6ca.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_1/bd_b6ca_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_2/bd_b6ca_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_3/bd_b6ca_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_4/bd_b6ca_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_5/bd_b6ca_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_6/bd_b6ca_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_7/bd_b6ca_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_8/bd_b6ca_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_9/bd_b6ca_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_1/bd_b6ca_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_5/bd_b6ca_s00a2s_0_ooc.xdc

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_6/bd_b6ca_sarn_0_ooc.xdc

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_7/bd_b6ca_srn_0_ooc.xdc

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_8/bd_b6ca_m00s2a_0_ooc.xdc

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_design_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_design_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
