
wire kernel_monitor_reset;
wire kernel_monitor_clock;
wire kernel_monitor_report;
assign kernel_monitor_reset = ~ap_rst_n;
assign kernel_monitor_clock = ap_clk;
assign kernel_monitor_report = 1'b0;
wire [0:0] axis_block_sigs;
wire [6:0] inst_idle_sigs;
wire [2:0] inst_block_sigs;
wire kernel_block;

assign axis_block_sigs[0] = ~grp_FrmbufRdHlsDataFlow_fu_178.MultiPixStream2AXIvideo_U0.grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_376_3_fu_138.m_axis_video_TDATA_blk_n;

assign inst_idle_sigs[0] = grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.ap_idle;
assign inst_block_sigs[0] = (grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.ap_done & ~grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.ap_continue) | ~grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.grp_AXIMMvideo2Bytes_Pipeline_VITIS_LOOP_625_4_fu_260.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.grp_AXIMMvideo2Bytes_Pipeline_VITIS_LOOP_591_1_fu_290.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.grp_AXIMMvideo2Bytes_Pipeline_VITIS_LOOP_660_7_fu_320.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.grp_AXIMMvideo2Bytes_Pipeline_VITIS_LOOP_634_5_fu_270.bytePlanes_plane1_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.grp_AXIMMvideo2Bytes_Pipeline_VITIS_LOOP_597_2_fu_300.bytePlanes_plane1_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.grp_AXIMMvideo2Bytes_Pipeline_VITIS_LOOP_670_8_fu_330.bytePlanes_plane1_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.grp_AXIMMvideo2Bytes_Pipeline_VITIS_LOOP_640_6_fu_280.bytePlanes_plane2_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.AXIMMvideo2Bytes_U0.grp_AXIMMvideo2Bytes_Pipeline_VITIS_LOOP_603_3_fu_310.bytePlanes_plane2_blk_n;
assign inst_idle_sigs[1] = grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.ap_idle;
assign inst_block_sigs[1] = (grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.ap_done & ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.ap_continue) | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1772_29_fu_302.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1532_26_fu_313.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_23_fu_330.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1398_20_fu_341.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_17_fu_360.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1197_14_fu_379.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1157_11_fu_392.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_954_8_fu_405.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_862_5_fu_426.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_755_1_fu_450.bytePlanes_plane0_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_954_8_fu_405.bytePlanes_plane1_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_862_5_fu_426.bytePlanes_plane1_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_755_1_fu_450.bytePlanes_plane1_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_862_5_fu_426.bytePlanes_plane2_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_755_1_fu_450.bytePlanes_plane2_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1772_29_fu_302.img_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1532_26_fu_313.img_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_23_fu_330.img_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1398_20_fu_341.img_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1240_17_fu_360.img_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1197_14_fu_379.img_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1157_11_fu_392.img_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_954_8_fu_405.img_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_862_5_fu_426.img_blk_n | ~grp_FrmbufRdHlsDataFlow_fu_178.Bytes2MultiPixStream_U0.grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_755_1_fu_450.img_blk_n;
assign inst_idle_sigs[2] = grp_FrmbufRdHlsDataFlow_fu_178.MultiPixStream2AXIvideo_U0.ap_idle;
assign inst_block_sigs[2] = (grp_FrmbufRdHlsDataFlow_fu_178.MultiPixStream2AXIvideo_U0.ap_done & ~grp_FrmbufRdHlsDataFlow_fu_178.MultiPixStream2AXIvideo_U0.ap_continue) | ~grp_FrmbufRdHlsDataFlow_fu_178.MultiPixStream2AXIvideo_U0.grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_376_3_fu_138.img_blk_n;

assign inst_idle_sigs[3] = 1'b0;
assign inst_idle_sigs[4] = grp_FrmbufRdHlsDataFlow_fu_178.ap_idle;
assign inst_idle_sigs[5] = grp_FrmbufRdHlsDataFlow_fu_178.MultiPixStream2AXIvideo_U0.ap_idle;
assign inst_idle_sigs[6] = grp_FrmbufRdHlsDataFlow_fu_178.MultiPixStream2AXIvideo_U0.grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_376_3_fu_138.ap_idle;

design_1_v_frmbuf_rd_0_0_hls_deadlock_idx0_monitor design_1_v_frmbuf_rd_0_0_hls_deadlock_idx0_monitor_U (
    .clock(kernel_monitor_clock),
    .reset(kernel_monitor_reset),
    .axis_block_sigs(axis_block_sigs),
    .inst_idle_sigs(inst_idle_sigs),
    .inst_block_sigs(inst_block_sigs),
    .block(kernel_block)
);


always @ (kernel_block or kernel_monitor_reset) begin
    if (kernel_block == 1'b1 && kernel_monitor_reset == 1'b0) begin
        find_kernel_block = 1'b1;
    end
    else begin
        find_kernel_block = 1'b0;
    end
end
