// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module top_design_v_frmbuf_rd_0_0_Bytes2MultiPixStream (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        bytePlanes_dout,
        bytePlanes_empty_n,
        bytePlanes_read,
        bytePlanes_num_data_valid,
        bytePlanes_fifo_cap,
        img_din,
        img_full_n,
        img_write,
        img_num_data_valid,
        img_fifo_cap,
        Height_val,
        WidthInBytes_val,
        VideoFormat_val
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] bytePlanes_dout;
input   bytePlanes_empty_n;
output   bytePlanes_read;
input  [9:0] bytePlanes_num_data_valid;
input  [9:0] bytePlanes_fifo_cap;
output  [23:0] img_din;
input   img_full_n;
output   img_write;
input  [31:0] img_num_data_valid;
input  [31:0] img_fifo_cap;
input  [10:0] Height_val;
input  [13:0] WidthInBytes_val;
input  [5:0] VideoFormat_val;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [5:0] VideoFormat_val_read_read_fu_128_p2;
reg   [5:0] VideoFormat_val_read_reg_270;
reg    ap_block_state1;
reg   [10:0] Height_val_read_reg_274;
wire   [10:0] trunc_ln1437_1_fu_213_p4;
reg   [10:0] trunc_ln1437_1_reg_286;
wire   [0:0] xor_ln1440_fu_235_p2;
reg   [0:0] xor_ln1440_reg_291;
wire   [11:0] add_ln1467_fu_241_p2;
reg   [11:0] add_ln1467_reg_296;
wire   [10:0] y_2_fu_260_p2;
reg   [10:0] y_2_reg_304;
wire    ap_CS_fsm_state2;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_start;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_done;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_idle;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_ready;
wire   [23:0] grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_img_din;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_img_write;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_bytePlanes_read;
reg    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_start_reg;
wire   [0:0] icmp_ln1443_fu_255_p2;
wire    ap_CS_fsm_state3;
reg   [10:0] y_fu_124;
wire    ap_CS_fsm_state4;
wire   [13:0] add_ln1437_fu_207_p2;
wire   [0:0] tmp_7_fu_227_p3;
wire   [11:0] zext_ln1437_fu_223_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 VideoFormat_val_read_reg_270 = 6'd0;
#0 Height_val_read_reg_274 = 11'd0;
#0 trunc_ln1437_1_reg_286 = 11'd0;
#0 xor_ln1440_reg_291 = 1'd0;
#0 add_ln1467_reg_296 = 12'd0;
#0 y_2_reg_304 = 11'd0;
#0 grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_start_reg = 1'b0;
#0 y_fu_124 = 11'd0;
end

top_design_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1 grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_start),
    .ap_done(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_done),
    .ap_idle(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_idle),
    .ap_ready(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_ready),
    .img_din(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_img_din),
    .img_full_n(img_full_n),
    .img_write(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_img_write),
    .img_num_data_valid(img_num_data_valid),
    .img_fifo_cap(img_fifo_cap),
    .bytePlanes_dout(bytePlanes_dout),
    .bytePlanes_empty_n(bytePlanes_empty_n),
    .bytePlanes_read(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_bytePlanes_read),
    .bytePlanes_num_data_valid(10'd0),
    .bytePlanes_fifo_cap(10'd0),
    .trunc_ln1437_1(trunc_ln1437_1_reg_286),
    .add_ln1467(add_ln1467_reg_296),
    .rev(xor_ln1440_reg_291)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Height_val_read_reg_274 <= 11'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            Height_val_read_reg_274 <= Height_val;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        VideoFormat_val_read_reg_270 <= 6'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            VideoFormat_val_read_reg_270 <= VideoFormat_val;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        add_ln1467_reg_296 <= 12'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            add_ln1467_reg_296 <= add_ln1467_fu_241_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & ((6'd43 == VideoFormat_val_read_reg_270) | ((6'd42 == VideoFormat_val_read_reg_270) | ((6'd44 == VideoFormat_val_read_reg_270) | ((6'd41 == VideoFormat_val_read_reg_270) | ((6'd19 == VideoFormat_val_read_reg_270) | ((6'd18 == VideoFormat_val_read_reg_270) | ((6'd23 == VideoFormat_val_read_reg_270) | ((6'd22 == VideoFormat_val_read_reg_270) | ((6'd33 == VideoFormat_val_read_reg_270) | ((6'd32 == VideoFormat_val_read_reg_270) | ((6'd38 == VideoFormat_val_read_reg_270) | ((6'd37 == VideoFormat_val_read_reg_270) | ((6'd12 == VideoFormat_val_read_reg_270) | ((6'd28 == VideoFormat_val_read_reg_270) | ((6'd21 == VideoFormat_val_read_reg_270) | ((6'd20 == VideoFormat_val_read_reg_270) | ((6'd31 == VideoFormat_val_read_reg_270) | ((6'd30 == VideoFormat_val_read_reg_270) | ((6'd36 == VideoFormat_val_read_reg_270) | ((6'd35 == VideoFormat_val_read_reg_270) | ((6'd29 == VideoFormat_val_read_reg_270) | ((icmp_ln1443_fu_255_p2 == 1'd1) | (~(6'd11 == VideoFormat_val_read_reg_270) & ~(6'd10 == VideoFormat_val_read_reg_270)))))))))))))))))))))))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (((6'd11 == VideoFormat_val_read_reg_270) & (icmp_ln1443_fu_255_p2 == 1'd0)) | ((icmp_ln1443_fu_255_p2 == 1'd0) & (6'd10 == VideoFormat_val_read_reg_270))))) begin
            grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_start_reg <= 1'b1;
        end else if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_ready == 1'b1)) begin
            grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln1437_1_reg_286 <= 11'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            trunc_ln1437_1_reg_286 <= {{add_ln1437_fu_207_p2[13:3]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        xor_ln1440_reg_291 <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            xor_ln1440_reg_291 <= xor_ln1440_fu_235_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        y_2_reg_304 <= 11'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            y_2_reg_304 <= y_2_fu_260_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        y_fu_124 <= 11'd0;
    end else begin
        if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & ((6'd11 == VideoFormat_val_read_read_fu_128_p2) | (6'd10 == VideoFormat_val_read_read_fu_128_p2)))) begin
            y_fu_124 <= 11'd0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            y_fu_124 <= y_2_reg_304;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((6'd43 == VideoFormat_val_read_reg_270) | ((6'd42 == VideoFormat_val_read_reg_270) | ((6'd44 == VideoFormat_val_read_reg_270) | ((6'd41 == VideoFormat_val_read_reg_270) | ((6'd19 == VideoFormat_val_read_reg_270) | ((6'd18 == VideoFormat_val_read_reg_270) | ((6'd23 == VideoFormat_val_read_reg_270) | ((6'd22 == VideoFormat_val_read_reg_270) | ((6'd33 == VideoFormat_val_read_reg_270) | ((6'd32 == VideoFormat_val_read_reg_270) | ((6'd38 == VideoFormat_val_read_reg_270) | ((6'd37 == VideoFormat_val_read_reg_270) | ((6'd12 == VideoFormat_val_read_reg_270) | ((6'd28 == VideoFormat_val_read_reg_270) | ((6'd21 == VideoFormat_val_read_reg_270) | ((6'd20 == VideoFormat_val_read_reg_270) | ((6'd31 == VideoFormat_val_read_reg_270) | ((6'd30 == VideoFormat_val_read_reg_270) | ((6'd36 == VideoFormat_val_read_reg_270) | ((6'd35 == VideoFormat_val_read_reg_270) | ((6'd29 == VideoFormat_val_read_reg_270) | ((icmp_ln1443_fu_255_p2 == 1'd1) | (~(6'd11 == VideoFormat_val_read_reg_270) & ~(6'd10 == VideoFormat_val_read_reg_270)))))))))))))))))))))))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((6'd43 == VideoFormat_val_read_reg_270) | ((6'd42 == VideoFormat_val_read_reg_270) | ((6'd44 == VideoFormat_val_read_reg_270) | ((6'd41 == VideoFormat_val_read_reg_270) | ((6'd19 == VideoFormat_val_read_reg_270) | ((6'd18 == VideoFormat_val_read_reg_270) | ((6'd23 == VideoFormat_val_read_reg_270) | ((6'd22 == VideoFormat_val_read_reg_270) | ((6'd33 == VideoFormat_val_read_reg_270) | ((6'd32 == VideoFormat_val_read_reg_270) | ((6'd38 == VideoFormat_val_read_reg_270) | ((6'd37 == VideoFormat_val_read_reg_270) | ((6'd12 == VideoFormat_val_read_reg_270) | ((6'd28 == VideoFormat_val_read_reg_270) | ((6'd21 == VideoFormat_val_read_reg_270) | ((6'd20 == VideoFormat_val_read_reg_270) | ((6'd31 == VideoFormat_val_read_reg_270) | ((6'd30 == VideoFormat_val_read_reg_270) | ((6'd36 == VideoFormat_val_read_reg_270) | ((6'd35 == VideoFormat_val_read_reg_270) | ((6'd29 == VideoFormat_val_read_reg_270) | ((icmp_ln1443_fu_255_p2 == 1'd1) | (~(6'd11 == VideoFormat_val_read_reg_270) & ~(6'd10 == VideoFormat_val_read_reg_270)))))))))))))))))))))))))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((6'd43 == VideoFormat_val_read_reg_270) | ((6'd42 == VideoFormat_val_read_reg_270) | ((6'd44 == VideoFormat_val_read_reg_270) | ((6'd41 == VideoFormat_val_read_reg_270) | ((6'd19 == VideoFormat_val_read_reg_270) | ((6'd18 == VideoFormat_val_read_reg_270) | ((6'd23 == VideoFormat_val_read_reg_270) | ((6'd22 == VideoFormat_val_read_reg_270) | ((6'd33 == VideoFormat_val_read_reg_270) | ((6'd32 == VideoFormat_val_read_reg_270) | ((6'd38 == VideoFormat_val_read_reg_270) | ((6'd37 == VideoFormat_val_read_reg_270) | ((6'd12 == VideoFormat_val_read_reg_270) | ((6'd28 == VideoFormat_val_read_reg_270) | ((6'd21 == VideoFormat_val_read_reg_270) | ((6'd20 == VideoFormat_val_read_reg_270) | ((6'd31 == VideoFormat_val_read_reg_270) | ((6'd30 == VideoFormat_val_read_reg_270) | ((6'd36 == VideoFormat_val_read_reg_270) | ((6'd35 == VideoFormat_val_read_reg_270) | ((6'd29 == VideoFormat_val_read_reg_270) | ((icmp_ln1443_fu_255_p2 == 1'd1) | (~(6'd11 == VideoFormat_val_read_reg_270) & ~(6'd10 == VideoFormat_val_read_reg_270)))))))))))))))))))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign VideoFormat_val_read_read_fu_128_p2 = VideoFormat_val;

assign add_ln1437_fu_207_p2 = (WidthInBytes_val + 14'd7);

assign add_ln1467_fu_241_p2 = ($signed(zext_ln1437_fu_223_p1) + $signed(12'd4095));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bytePlanes_read = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_bytePlanes_read;

assign grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_start = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_ap_start_reg;

assign icmp_ln1443_fu_255_p2 = ((y_fu_124 == Height_val_read_reg_274) ? 1'b1 : 1'b0);

assign img_din = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_img_din;

assign img_write = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1450_1_fu_146_img_write;

assign start_out = real_start;

assign tmp_7_fu_227_p3 = WidthInBytes_val[32'd2];

assign trunc_ln1437_1_fu_213_p4 = {{add_ln1437_fu_207_p2[13:3]}};

assign xor_ln1440_fu_235_p2 = (tmp_7_fu_227_p3 ^ 1'd1);

assign y_2_fu_260_p2 = (y_fu_124 + 11'd1);

assign zext_ln1437_fu_223_p1 = trunc_ln1437_1_fu_213_p4;

endmodule //top_design_v_frmbuf_rd_0_0_Bytes2MultiPixStream
