// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module top_design_v_mix_0_0_AXIMMvideo2Bytes_1_Pipeline_VITIS_LOOP_203_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_mm_video1_0_AWVALID,
        m_axi_mm_video1_0_AWREADY,
        m_axi_mm_video1_0_AWADDR,
        m_axi_mm_video1_0_AWID,
        m_axi_mm_video1_0_AWLEN,
        m_axi_mm_video1_0_AWSIZE,
        m_axi_mm_video1_0_AWBURST,
        m_axi_mm_video1_0_AWLOCK,
        m_axi_mm_video1_0_AWCACHE,
        m_axi_mm_video1_0_AWPROT,
        m_axi_mm_video1_0_AWQOS,
        m_axi_mm_video1_0_AWREGION,
        m_axi_mm_video1_0_AWUSER,
        m_axi_mm_video1_0_WVALID,
        m_axi_mm_video1_0_WREADY,
        m_axi_mm_video1_0_WDATA,
        m_axi_mm_video1_0_WSTRB,
        m_axi_mm_video1_0_WLAST,
        m_axi_mm_video1_0_WID,
        m_axi_mm_video1_0_WUSER,
        m_axi_mm_video1_0_ARVALID,
        m_axi_mm_video1_0_ARREADY,
        m_axi_mm_video1_0_ARADDR,
        m_axi_mm_video1_0_ARID,
        m_axi_mm_video1_0_ARLEN,
        m_axi_mm_video1_0_ARSIZE,
        m_axi_mm_video1_0_ARBURST,
        m_axi_mm_video1_0_ARLOCK,
        m_axi_mm_video1_0_ARCACHE,
        m_axi_mm_video1_0_ARPROT,
        m_axi_mm_video1_0_ARQOS,
        m_axi_mm_video1_0_ARREGION,
        m_axi_mm_video1_0_ARUSER,
        m_axi_mm_video1_0_RVALID,
        m_axi_mm_video1_0_RREADY,
        m_axi_mm_video1_0_RDATA,
        m_axi_mm_video1_0_RLAST,
        m_axi_mm_video1_0_RID,
        m_axi_mm_video1_0_RFIFONUM,
        m_axi_mm_video1_0_RUSER,
        m_axi_mm_video1_0_RRESP,
        m_axi_mm_video1_0_BVALID,
        m_axi_mm_video1_0_BREADY,
        m_axi_mm_video1_0_BRESP,
        m_axi_mm_video1_0_BID,
        m_axi_mm_video1_0_BUSER,
        bytesLayer1_plane0_din,
        bytesLayer1_plane0_full_n,
        bytesLayer1_plane0_write,
        bytesLayer1_plane0_num_data_valid,
        bytesLayer1_plane0_fifo_cap,
        loopWidth_i,
        sext_ln203_i
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_mm_video1_0_AWVALID;
input   m_axi_mm_video1_0_AWREADY;
output  [31:0] m_axi_mm_video1_0_AWADDR;
output  [0:0] m_axi_mm_video1_0_AWID;
output  [31:0] m_axi_mm_video1_0_AWLEN;
output  [2:0] m_axi_mm_video1_0_AWSIZE;
output  [1:0] m_axi_mm_video1_0_AWBURST;
output  [1:0] m_axi_mm_video1_0_AWLOCK;
output  [3:0] m_axi_mm_video1_0_AWCACHE;
output  [2:0] m_axi_mm_video1_0_AWPROT;
output  [3:0] m_axi_mm_video1_0_AWQOS;
output  [3:0] m_axi_mm_video1_0_AWREGION;
output  [0:0] m_axi_mm_video1_0_AWUSER;
output   m_axi_mm_video1_0_WVALID;
input   m_axi_mm_video1_0_WREADY;
output  [63:0] m_axi_mm_video1_0_WDATA;
output  [7:0] m_axi_mm_video1_0_WSTRB;
output   m_axi_mm_video1_0_WLAST;
output  [0:0] m_axi_mm_video1_0_WID;
output  [0:0] m_axi_mm_video1_0_WUSER;
output   m_axi_mm_video1_0_ARVALID;
input   m_axi_mm_video1_0_ARREADY;
output  [31:0] m_axi_mm_video1_0_ARADDR;
output  [0:0] m_axi_mm_video1_0_ARID;
output  [31:0] m_axi_mm_video1_0_ARLEN;
output  [2:0] m_axi_mm_video1_0_ARSIZE;
output  [1:0] m_axi_mm_video1_0_ARBURST;
output  [1:0] m_axi_mm_video1_0_ARLOCK;
output  [3:0] m_axi_mm_video1_0_ARCACHE;
output  [2:0] m_axi_mm_video1_0_ARPROT;
output  [3:0] m_axi_mm_video1_0_ARQOS;
output  [3:0] m_axi_mm_video1_0_ARREGION;
output  [0:0] m_axi_mm_video1_0_ARUSER;
input   m_axi_mm_video1_0_RVALID;
output   m_axi_mm_video1_0_RREADY;
input  [63:0] m_axi_mm_video1_0_RDATA;
input   m_axi_mm_video1_0_RLAST;
input  [0:0] m_axi_mm_video1_0_RID;
input  [6:0] m_axi_mm_video1_0_RFIFONUM;
input  [0:0] m_axi_mm_video1_0_RUSER;
input  [1:0] m_axi_mm_video1_0_RRESP;
input   m_axi_mm_video1_0_BVALID;
output   m_axi_mm_video1_0_BREADY;
input  [1:0] m_axi_mm_video1_0_BRESP;
input  [0:0] m_axi_mm_video1_0_BID;
input  [0:0] m_axi_mm_video1_0_BUSER;
output  [63:0] bytesLayer1_plane0_din;
input   bytesLayer1_plane0_full_n;
output   bytesLayer1_plane0_write;
input  [2:0] bytesLayer1_plane0_num_data_valid;
input  [2:0] bytesLayer1_plane0_fifo_cap;
input  [13:0] loopWidth_i;
input  [28:0] sext_ln203_i;

reg ap_idle;
reg m_axi_mm_video1_0_RREADY;
reg bytesLayer1_plane0_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln203_fu_108_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mm_video1_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
reg    bytesLayer1_plane0_blk_n;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] mm_video1_addr_read_reg_147;
reg   [13:0] x_fu_68;
wire   [13:0] add_ln203_fu_114_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_x_21;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 x_fu_68 = 14'd0;
#0 ap_done_reg = 1'b0;
end

top_design_v_mix_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln203_fu_108_p2 == 1'd0))) begin
            x_fu_68 <= add_ln203_fu_114_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_68 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mm_video1_addr_read_reg_147 <= m_axi_mm_video1_0_RDATA;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln203_fu_108_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_21 = 14'd0;
    end else begin
        ap_sig_allocacmp_x_21 = x_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bytesLayer1_plane0_blk_n = bytesLayer1_plane0_full_n;
    end else begin
        bytesLayer1_plane0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bytesLayer1_plane0_write = 1'b1;
    end else begin
        bytesLayer1_plane0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_mm_video1_0_RREADY = 1'b1;
    end else begin
        m_axi_mm_video1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mm_video1_blk_n_R = m_axi_mm_video1_0_RVALID;
    end else begin
        mm_video1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln203_fu_114_p2 = (ap_sig_allocacmp_x_21 + 14'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((bytesLayer1_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((m_axi_mm_video1_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((bytesLayer1_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((m_axi_mm_video1_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((bytesLayer1_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((m_axi_mm_video1_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((bytesLayer1_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((m_axi_mm_video1_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bytesLayer1_plane0_din = mm_video1_addr_read_reg_147;

assign icmp_ln203_fu_108_p2 = ((ap_sig_allocacmp_x_21 == loopWidth_i) ? 1'b1 : 1'b0);

assign m_axi_mm_video1_0_ARADDR = 32'd0;

assign m_axi_mm_video1_0_ARBURST = 2'd0;

assign m_axi_mm_video1_0_ARCACHE = 4'd0;

assign m_axi_mm_video1_0_ARID = 1'd0;

assign m_axi_mm_video1_0_ARLEN = 32'd0;

assign m_axi_mm_video1_0_ARLOCK = 2'd0;

assign m_axi_mm_video1_0_ARPROT = 3'd0;

assign m_axi_mm_video1_0_ARQOS = 4'd0;

assign m_axi_mm_video1_0_ARREGION = 4'd0;

assign m_axi_mm_video1_0_ARSIZE = 3'd0;

assign m_axi_mm_video1_0_ARUSER = 1'd0;

assign m_axi_mm_video1_0_ARVALID = 1'b0;

assign m_axi_mm_video1_0_AWADDR = 32'd0;

assign m_axi_mm_video1_0_AWBURST = 2'd0;

assign m_axi_mm_video1_0_AWCACHE = 4'd0;

assign m_axi_mm_video1_0_AWID = 1'd0;

assign m_axi_mm_video1_0_AWLEN = 32'd0;

assign m_axi_mm_video1_0_AWLOCK = 2'd0;

assign m_axi_mm_video1_0_AWPROT = 3'd0;

assign m_axi_mm_video1_0_AWQOS = 4'd0;

assign m_axi_mm_video1_0_AWREGION = 4'd0;

assign m_axi_mm_video1_0_AWSIZE = 3'd0;

assign m_axi_mm_video1_0_AWUSER = 1'd0;

assign m_axi_mm_video1_0_AWVALID = 1'b0;

assign m_axi_mm_video1_0_BREADY = 1'b0;

assign m_axi_mm_video1_0_WDATA = 64'd0;

assign m_axi_mm_video1_0_WID = 1'd0;

assign m_axi_mm_video1_0_WLAST = 1'b0;

assign m_axi_mm_video1_0_WSTRB = 8'd0;

assign m_axi_mm_video1_0_WUSER = 1'd0;

assign m_axi_mm_video1_0_WVALID = 1'b0;

endmodule //top_design_v_mix_0_0_AXIMMvideo2Bytes_1_Pipeline_VITIS_LOOP_203_2
