[hls]
relative_roots=/home/serg/Documents/Xilinx/z700_hdmi/HDMI_VMIX/hdmi_vmix.runs/top_design_v_mix_0_0_synth_1
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=v_mix/VITIS_LOOP_3296_1 


