set_property SRC_FILE_INFO {cfile:/home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc rfile:../../../../../alinx_video.gen/sources_1/bd/top_design/ip/top_design_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc id:1 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_rgb2dvi_0_0/src/rgb2dvi.xdc rfile:../../../../../alinx_video.gen/sources_1/bd/top_design/ip/top_design_rgb2dvi_0_0/src/rgb2dvi.xdc id:2 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.runs/top_design_rgb2dvi_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 6.060 -name PixelClk [get_ports PixelClk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_generated_clock -name SerialClk -source [get_ports PixelClk] -multiply_by 5 [get_ports SerialClk]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins [list {U0/LockLostReset/SyncAsyncx/oSyncStages_reg[0]/PRE} {U0/LockLostReset/SyncAsyncx/oSyncStages_reg[1]/PRE}]]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins {U0/LockLostReset/SyncAsyncx/oSyncStages_reg[0]/D}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells U0]
