# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Sergey/Documents/Xilinx/z7000_hdmi/HDMI_FBWRRD/HDMI_FBWRRD.srcs/sources_1/bd/top_design/ip/top_design_v_tpg_0_0_2/top_design_v_tpg_0_0.xci
# IP: The module: 'top_design_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sergey/Documents/Xilinx/z7000_hdmi/HDMI_FBWRRD/HDMI_FBWRRD.gen/sources_1/bd/top_design/ip/top_design_v_tpg_0_0_2/top_design_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_design_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Sergey/Documents/Xilinx/z7000_hdmi/HDMI_FBWRRD/HDMI_FBWRRD.gen/sources_1/bd/top_design/ip/top_design_v_tpg_0_0_2/top_design_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_design_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Sergey/Documents/Xilinx/z7000_hdmi/HDMI_FBWRRD/HDMI_FBWRRD.srcs/sources_1/bd/top_design/ip/top_design_v_tpg_0_0_2/top_design_v_tpg_0_0.xci
# IP: The module: 'top_design_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sergey/Documents/Xilinx/z7000_hdmi/HDMI_FBWRRD/HDMI_FBWRRD.gen/sources_1/bd/top_design/ip/top_design_v_tpg_0_0_2/top_design_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_design_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Sergey/Documents/Xilinx/z7000_hdmi/HDMI_FBWRRD/HDMI_FBWRRD.gen/sources_1/bd/top_design/ip/top_design_v_tpg_0_0_2/top_design_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_design_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
