# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.runs/synth_1/top_design_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param bd.open.in_stealth_mode 2
set_param chipscope.maxJobs 4
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.cache/wt [current_project]
set_property parent.project_path /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/serg/Documents/Xilinx/DigilentLib/vivado-library-master [current_project]
update_ip_catalog
set_property ip_output_repo /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/hdl/top_design_wrapper.v
add_files /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.srcs/sources_1/bd/top_design/top_design.bd
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_processing_system7_0_0/top_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_tpg_0_1/top_design_v_tpg_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_tpg_0_1/top_design_v_tpg_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_1/bd_b6ca_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_2/bd_b6ca_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_3/bd_b6ca_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_4/bd_b6ca_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_5/bd_b6ca_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_6/bd_b6ca_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_7/bd_b6ca_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_8/bd_b6ca_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_9/bd_b6ca_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_10/bd_b6ca_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_11/bd_b6ca_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_12/bd_b6ca_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_13/bd_b6ca_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_14/bd_b6ca_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_15/bd_b6ca_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_16/bd_b6ca_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_17/bd_b6ca_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_18/bd_b6ca_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_22/bd_b6ca_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_23/bd_b6ca_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_24/bd_b6ca_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_25/bd_b6ca_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_26/bd_b6ca_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_27/bd_b6ca_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_28/bd_b6ca_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_29/bd_b6ca_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_30/bd_b6ca_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_31/bd_b6ca_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_32/bd_b6ca_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_33/bd_b6ca_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_35/bd_b6ca_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_36/bd_b6ca_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_37/bd_b6ca_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_38/bd_b6ca_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_39/bd_b6ca_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_40/bd_b6ca_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_42/bd_b6ca_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_43/bd_b6ca_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_44/bd_b6ca_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_45/bd_b6ca_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_46/bd_b6ca_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_47/bd_b6ca_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_49/bd_b6ca_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_50/bd_b6ca_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_51/bd_b6ca_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_52/bd_b6ca_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_53/bd_b6ca_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_54/bd_b6ca_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_56/bd_b6ca_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_57/bd_b6ca_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_58/bd_b6ca_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_59/bd_b6ca_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_60/bd_b6ca_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_61/bd_b6ca_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_63/bd_b6ca_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_64/bd_b6ca_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_65/bd_b6ca_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_66/bd_b6ca_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_67/bd_b6ca_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_68/bd_b6ca_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_70/bd_b6ca_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_71/bd_b6ca_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_72/bd_b6ca_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_73/bd_b6ca_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_74/bd_b6ca_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/bd_0/ip/ip_75/bd_b6ca_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_smc_1/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_rst_ps7_0_148M_1/top_design_rst_ps7_0_148M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_rst_ps7_0_148M_1/top_design_rst_ps7_0_148M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_axi4s_vid_out_0_1/top_design_v_axi4s_vid_out_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_axi4s_vid_out_0_1/top_design_v_axi4s_vid_out_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_tc_0_1/top_design_v_tc_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_tc_0_1/top_design_v_tc_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axi_dynclk_0_0/src/axi_dynclk.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_rst_ps7_0_148M_2/top_design_rst_ps7_0_148M_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_rst_ps7_0_148M_2/top_design_rst_ps7_0_148M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_frmbuf_wr_0_0/top_design_v_frmbuf_wr_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_frmbuf_wr_0_0/top_design_v_frmbuf_wr_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_frmbuf_rd_0_0/top_design_v_frmbuf_rd_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_frmbuf_rd_0_0/top_design_v_frmbuf_rd_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_1/bd_8df6_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_2/bd_8df6_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_3/bd_8df6_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_4/bd_8df6_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_5/bd_8df6_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_6/bd_8df6_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_10/bd_8df6_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_11/bd_8df6_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_12/bd_8df6_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_13/bd_8df6_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_14/bd_8df6_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_15/bd_8df6_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_19/bd_8df6_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_20/bd_8df6_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_21/bd_8df6_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_22/bd_8df6_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_23/bd_8df6_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_24/bd_8df6_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_28/bd_8df6_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_29/bd_8df6_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_30/bd_8df6_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_31/bd_8df6_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_32/bd_8df6_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_33/bd_8df6_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_34/bd_8df6_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_35/bd_8df6_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_36/bd_8df6_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_37/bd_8df6_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_38/bd_8df6_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/bd_0/ip/ip_39/bd_8df6_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_mix_0_0/top_design_v_mix_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_mix_0_0/top_design_v_mix_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axis_switch_0_0/top_design_axis_switch_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_vid_in_axi4s_0_0/top_design_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_v_vid_in_axi4s_0_0/top_design_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/ip/top_design_axis_subset_converter_0_0/top_design_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.gen/sources_1/bd/top_design/top_design_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.srcs/constrs_1/new/phy_constr.xdc
set_property used_in_implementation false [get_files /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.srcs/constrs_1/new/phy_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/serg/Documents/Xilinx/z700_hdmi/ALINX_VIDEO/alinx_video.srcs/utils_1/imports/synth_1/top_design_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_design_wrapper -part xc7z020clg400-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_design_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_design_wrapper_utilization_synth.rpt -pb top_design_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
