[hls]
relative_roots=/home/serg/Documents/Xilinx/z700_hdmi/HDMI_TEST_TPG/HDMI_TEST.runs/top_design_v_frmbuf_rd_0_0_synth_1
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=multipixstream2axivideo/VITIS_LOOP_367_1 


