-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_mix_0_0_v_mix_core_alpha_true_true_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    outLayer0_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    outLayer0_empty_n : IN STD_LOGIC;
    outLayer0_read : OUT STD_LOGIC;
    outLayer0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    outLayer0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1x_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    srcLayer1x_empty_n : IN STD_LOGIC;
    srcLayer1x_read : OUT STD_LOGIC;
    srcLayer1x_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1x_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1Alphax_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    srcLayer1Alphax_empty_n : IN STD_LOGIC;
    srcLayer1Alphax_read : OUT STD_LOGIC;
    srcLayer1Alphax_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    srcLayer1Alphax_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    hwReg_width_val : IN STD_LOGIC_VECTOR (10 downto 0);
    hwReg_height_val : IN STD_LOGIC_VECTOR (10 downto 0);
    hwReg_background_Y_R_val : IN STD_LOGIC_VECTOR (7 downto 0);
    hwReg_background_U_G_val : IN STD_LOGIC_VECTOR (7 downto 0);
    hwReg_background_V_B_val : IN STD_LOGIC_VECTOR (7 downto 0);
    hwReg_layerEnable_val : IN STD_LOGIC_VECTOR (1 downto 0);
    hwReg_layerAlpha_1_val : IN STD_LOGIC_VECTOR (8 downto 0);
    hwReg_layerStartX_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    hwReg_layerStartY_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    hwReg_layerWidth_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    hwReg_layerHeight_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    hwReg_layerScaleFactor_1_val : IN STD_LOGIC_VECTOR (7 downto 0);
    outLayer1_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    outLayer1_full_n : IN STD_LOGIC;
    outLayer1_write : OUT STD_LOGIC;
    outLayer1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    outLayer1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of design_1_v_mix_0_0_v_mix_core_alpha_true_true_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal hwReg_layerStartY_1_val_read_reg_339 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal hwReg_layerStartX_1_val_read_reg_344 : STD_LOGIC_VECTOR (15 downto 0);
    signal hwReg_background_V_B_val_read_reg_349 : STD_LOGIC_VECTOR (7 downto 0);
    signal hwReg_background_U_G_val_read_reg_354 : STD_LOGIC_VECTOR (7 downto 0);
    signal hwReg_background_Y_R_val_read_reg_359 : STD_LOGIC_VECTOR (7 downto 0);
    signal hwReg_height_val_read_reg_364 : STD_LOGIC_VECTOR (10 downto 0);
    signal hwReg_width_val_read_reg_369 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_fu_209_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_374 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_reg_unsigned_short_s_fu_198_ap_return : STD_LOGIC_VECTOR (8 downto 0);
    signal alpha_reg_379 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln330_fu_241_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln330_reg_384 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln332_fu_255_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln332_reg_389 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_6_reg_394 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln330_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln330_reg_402 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln330_1_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln330_1_reg_407 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln330_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln330_reg_412 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_start : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_done : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_idle : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_ready : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_srcLayer1x_read : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_srcLayer1Alphax_read : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_outLayer0_read : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_outLayer1_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_outLayer1_write : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out1_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out1_o_ap_vld : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out2_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out2_o_ap_vld : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_198_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_198_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_198_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_198_ap_ready : STD_LOGIC;
    signal grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal p_lcssa2540_fu_92 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa2437_fu_88 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa2334_fu_84 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1_ignore_call37 : BOOLEAN;
    signal y_fu_96 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln314_fu_277_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln314_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hwReg_layerScaleFactor_1_val_readcast_fu_213_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal hwReg_layerScaleFactor_1_val_readcast30_fu_223_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln296_fu_217_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln330_1_fu_237_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln330_fu_233_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln297_fu_227_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln332_1_fu_251_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln332_fu_247_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln314_1_fu_287_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln314_fu_283_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_mix_0_0_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        srcLayer1x_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        srcLayer1x_empty_n : IN STD_LOGIC;
        srcLayer1x_read : OUT STD_LOGIC;
        srcLayer1x_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1x_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1Alphax_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        srcLayer1Alphax_empty_n : IN STD_LOGIC;
        srcLayer1Alphax_read : OUT STD_LOGIC;
        srcLayer1Alphax_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        srcLayer1Alphax_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        outLayer0_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        outLayer0_empty_n : IN STD_LOGIC;
        outLayer0_read : OUT STD_LOGIC;
        outLayer0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        outLayer0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        outLayer1_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        outLayer1_full_n : IN STD_LOGIC;
        outLayer1_write : OUT STD_LOGIC;
        outLayer1_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        outLayer1_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        hwReg_width_val : IN STD_LOGIC_VECTOR (10 downto 0);
        zext_ln346 : IN STD_LOGIC_VECTOR (8 downto 0);
        hwReg_background_Y_R_val : IN STD_LOGIC_VECTOR (7 downto 0);
        hwReg_background_U_G_val : IN STD_LOGIC_VECTOR (7 downto 0);
        hwReg_background_V_B_val : IN STD_LOGIC_VECTOR (7 downto 0);
        hwReg_layerStartX_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
        add_ln332 : IN STD_LOGIC_VECTOR (16 downto 0);
        icmp_ln330_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        rev7 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty_61 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        p_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_o_ap_vld : OUT STD_LOGIC;
        p_out1_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out1_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out1_o_ap_vld : OUT STD_LOGIC;
        p_out2_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out2_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out2_o_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_mix_0_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (8 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;



begin
    grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172 : component design_1_v_mix_0_0_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_start,
        ap_done => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_done,
        ap_idle => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_idle,
        ap_ready => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_ready,
        srcLayer1x_dout => srcLayer1x_dout,
        srcLayer1x_empty_n => srcLayer1x_empty_n,
        srcLayer1x_read => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_srcLayer1x_read,
        srcLayer1x_num_data_valid => ap_const_lv3_0,
        srcLayer1x_fifo_cap => ap_const_lv3_0,
        srcLayer1Alphax_dout => srcLayer1Alphax_dout,
        srcLayer1Alphax_empty_n => srcLayer1Alphax_empty_n,
        srcLayer1Alphax_read => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_srcLayer1Alphax_read,
        srcLayer1Alphax_num_data_valid => ap_const_lv5_0,
        srcLayer1Alphax_fifo_cap => ap_const_lv5_0,
        outLayer0_dout => outLayer0_dout,
        outLayer0_empty_n => outLayer0_empty_n,
        outLayer0_read => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_outLayer0_read,
        outLayer0_num_data_valid => ap_const_lv3_0,
        outLayer0_fifo_cap => ap_const_lv3_0,
        outLayer1_din => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_outLayer1_din,
        outLayer1_full_n => outLayer1_full_n,
        outLayer1_write => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_outLayer1_write,
        outLayer1_num_data_valid => outLayer1_num_data_valid,
        outLayer1_fifo_cap => outLayer1_fifo_cap,
        hwReg_width_val => hwReg_width_val_read_reg_369,
        zext_ln346 => alpha_reg_379,
        hwReg_background_Y_R_val => hwReg_background_Y_R_val_read_reg_359,
        hwReg_background_U_G_val => hwReg_background_U_G_val_read_reg_354,
        hwReg_background_V_B_val => hwReg_background_V_B_val_read_reg_349,
        hwReg_layerStartX_1_val => hwReg_layerStartX_1_val_read_reg_344,
        add_ln332 => add_ln332_reg_389,
        icmp_ln330_1 => icmp_ln330_1_reg_407,
        rev7 => xor_ln330_reg_412,
        empty_61 => tmp_6_reg_394,
        empty => empty_reg_374,
        p_out_i => p_lcssa2540_fu_92,
        p_out_o => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out_o,
        p_out_o_ap_vld => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out_o_ap_vld,
        p_out1_i => p_lcssa2437_fu_88,
        p_out1_o => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out1_o,
        p_out1_o_ap_vld => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out1_o_ap_vld,
        p_out2_i => p_lcssa2334_fu_84,
        p_out2_o => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out2_o,
        p_out2_o_ap_vld => grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out2_o_ap_vld);

    grp_reg_unsigned_short_s_fu_198 : component design_1_v_mix_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_198_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_198_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_198_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_198_ap_ready,
        d => hwReg_layerAlpha_1_val,
        ap_return => grp_reg_unsigned_short_s_fu_198_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln314_fu_272_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_ready = ap_const_logic_1)) then 
                    grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_96 <= ap_const_lv11_0;
            elsif (((icmp_ln314_fu_272_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                y_fu_96 <= add_ln314_fu_277_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln330_reg_384 <= add_ln330_fu_241_p2;
                add_ln332_reg_389 <= add_ln332_fu_255_p2;
                alpha_reg_379 <= grp_reg_unsigned_short_s_fu_198_ap_return;
                empty_reg_374 <= empty_fu_209_p1;
                hwReg_background_U_G_val_read_reg_354 <= hwReg_background_U_G_val;
                hwReg_background_V_B_val_read_reg_349 <= hwReg_background_V_B_val;
                hwReg_background_Y_R_val_read_reg_359 <= hwReg_background_Y_R_val;
                hwReg_height_val_read_reg_364 <= hwReg_height_val;
                hwReg_layerStartX_1_val_read_reg_344 <= hwReg_layerStartX_1_val;
                hwReg_layerStartY_1_val_read_reg_339 <= hwReg_layerStartY_1_val;
                hwReg_width_val_read_reg_369 <= hwReg_width_val;
                tmp_6_reg_394 <= hwReg_layerEnable_val(1 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                icmp_ln330_1_reg_407 <= icmp_ln330_1_fu_296_p2;
                icmp_ln330_reg_402 <= icmp_ln330_fu_291_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out2_o_ap_vld = ap_const_logic_1))) then
                p_lcssa2334_fu_84 <= grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out2_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out1_o_ap_vld = ap_const_logic_1))) then
                p_lcssa2437_fu_88 <= grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out_o_ap_vld = ap_const_logic_1))) then
                p_lcssa2540_fu_92 <= grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_p_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                xor_ln330_reg_412 <= xor_ln330_fu_306_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state3, grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_done, ap_CS_fsm_state5, icmp_ln314_fu_272_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln314_fu_272_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln314_fu_277_p2 <= std_logic_vector(unsigned(y_fu_96) + unsigned(ap_const_lv11_1));
    add_ln330_fu_241_p2 <= std_logic_vector(unsigned(zext_ln330_1_fu_237_p1) + unsigned(zext_ln330_fu_233_p1));
    add_ln332_fu_255_p2 <= std_logic_vector(unsigned(zext_ln332_1_fu_251_p1) + unsigned(zext_ln332_fu_247_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_done)
    begin
        if ((grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call37_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call37 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln314_fu_272_p2)
    begin
        if (((icmp_ln314_fu_272_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    empty_fu_209_p1 <= hwReg_layerEnable_val(1 - 1 downto 0);

    grp_reg_unsigned_short_s_fu_198_ap_start_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_ignore_call37)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_state1_ignore_call37) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_reg_unsigned_short_s_fu_198_ap_start <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_198_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_start <= grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_ap_start_reg;
    hwReg_layerScaleFactor_1_val_readcast30_fu_223_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hwReg_layerScaleFactor_1_val),16));
    hwReg_layerScaleFactor_1_val_readcast_fu_213_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hwReg_layerScaleFactor_1_val),16));
    icmp_ln314_fu_272_p2 <= "1" when (y_fu_96 = hwReg_height_val_read_reg_364) else "0";
    icmp_ln330_1_fu_296_p2 <= "1" when (unsigned(add_ln330_reg_384) > unsigned(zext_ln314_fu_283_p1)) else "0";
    icmp_ln330_fu_291_p2 <= "1" when (unsigned(zext_ln314_1_fu_287_p1) < unsigned(hwReg_layerStartY_1_val_read_reg_339)) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln314_fu_272_p2)
    begin
        if (((icmp_ln314_fu_272_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    outLayer0_read <= grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_outLayer0_read;
    outLayer1_din <= grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_outLayer1_din;
    outLayer1_write <= grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_outLayer1_write;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    shl_ln296_fu_217_p2 <= std_logic_vector(shift_left(unsigned(hwReg_layerHeight_1_val),to_integer(unsigned('0' & hwReg_layerScaleFactor_1_val_readcast_fu_213_p1(16-1 downto 0)))));
    shl_ln297_fu_227_p2 <= std_logic_vector(shift_left(unsigned(hwReg_layerWidth_1_val),to_integer(unsigned('0' & hwReg_layerScaleFactor_1_val_readcast30_fu_223_p1(16-1 downto 0)))));
    srcLayer1Alphax_read <= grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_srcLayer1Alphax_read;
    srcLayer1x_read <= grp_v_mix_core_alpha_true_true_Pipeline_VITIS_LOOP_316_3_fu_172_srcLayer1x_read;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln330_fu_306_p2 <= (icmp_ln330_reg_402 xor ap_const_lv1_1);
    zext_ln314_1_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_96),16));
    zext_ln314_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_96),17));
    zext_ln330_1_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln296_fu_217_p2),17));
    zext_ln330_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hwReg_layerStartY_1_val),17));
    zext_ln332_1_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln297_fu_227_p2),17));
    zext_ln332_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hwReg_layerStartX_1_val),17));
end behav;
