set SynModuleInfo {
  {SRCNAME {reg<unsigned short>} MODELNAME reg_unsigned_short_s RTLNAME design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s}
  {SRCNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start MODELNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start RTLNAME design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start
    SUBMODULES {
      {MODELNAME design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init RTLNAME design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME AXIvideo2MultiPixStream_Pipeline_loop_width MODELNAME AXIvideo2MultiPixStream_Pipeline_loop_width RTLNAME design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width}
  {SRCNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol MODELNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol RTLNAME design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol}
  {SRCNAME AXIvideo2MultiPixStream MODELNAME AXIvideo2MultiPixStream RTLNAME design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1380_34 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1380_34 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1380_34}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1333_29 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1333_29 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1333_29}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1090_24 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1090_24 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1090_24}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_904_21 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_904_21 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_904_21}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_863_18 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_863_18 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_863_18}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_821_14 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_821_14 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_821_14}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_739_11 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_739_11 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_739_11}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_697_7 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_697_7 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_697_7}
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_605_4 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_605_4 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_605_4
    SUBMODULES {
      {MODELNAME design_1_v_frmbuf_wr_0_0_partset_64ns_64ns_8ns_6ns_64_1_1 RTLNAME design_1_v_frmbuf_wr_0_0_partset_64ns_64ns_8ns_6ns_64_1_1 BINDTYPE op TYPE partset IMPL auto}
    }
  }
  {SRCNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1 MODELNAME MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1 RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1}
  {SRCNAME MultiPixStream2Bytes MODELNAME MultiPixStream2Bytes RTLNAME design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes
    SUBMODULES {
      {MODELNAME design_1_v_frmbuf_wr_0_0_mul_11ns_13ns_23_1_1 RTLNAME design_1_v_frmbuf_wr_0_0_mul_11ns_13ns_23_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1699_4 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1699_4 RTLNAME design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1699_4}
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1709_5 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1709_5 RTLNAME design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1709_5}
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1715_6 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1715_6 RTLNAME design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1715_6}
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1652_1 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1652_1 RTLNAME design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1652_1}
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1658_2 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1658_2 RTLNAME design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1658_2}
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1664_3 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1664_3 RTLNAME design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1664_3}
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1748_7 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1748_7 RTLNAME design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1748_7}
  {SRCNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1758_8 MODELNAME Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1758_8 RTLNAME design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1758_8}
  {SRCNAME Bytes2AXIMMvideo MODELNAME Bytes2AXIMMvideo RTLNAME design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo}
  {SRCNAME FrmbufWrHlsDataFlow MODELNAME FrmbufWrHlsDataFlow RTLNAME design_1_v_frmbuf_wr_0_0_FrmbufWrHlsDataFlow
    SUBMODULES {
      {MODELNAME design_1_v_frmbuf_wr_0_0_fifo_w24_d2_S RTLNAME design_1_v_frmbuf_wr_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME img_U}
      {MODELNAME design_1_v_frmbuf_wr_0_0_fifo_w64_d481_B RTLNAME design_1_v_frmbuf_wr_0_0_fifo_w64_d481_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME bytePlanes_plane0_U}
      {MODELNAME design_1_v_frmbuf_wr_0_0_fifo_w64_d481_B RTLNAME design_1_v_frmbuf_wr_0_0_fifo_w64_d481_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME bytePlanes_plane1_U}
      {MODELNAME design_1_v_frmbuf_wr_0_0_fifo_w64_d481_B RTLNAME design_1_v_frmbuf_wr_0_0_fifo_w64_d481_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME bytePlanes_plane2_U}
      {MODELNAME design_1_v_frmbuf_wr_0_0_start_for_MultiPixStream2Bytes_U0 RTLNAME design_1_v_frmbuf_wr_0_0_start_for_MultiPixStream2Bytes_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_MultiPixStream2Bytes_U0_U}
      {MODELNAME design_1_v_frmbuf_wr_0_0_start_for_Bytes2AXIMMvideo_U0 RTLNAME design_1_v_frmbuf_wr_0_0_start_for_Bytes2AXIMMvideo_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_Bytes2AXIMMvideo_U0_U}
    }
  }
  {SRCNAME v_frmbuf_wr MODELNAME v_frmbuf_wr RTLNAME design_1_v_frmbuf_wr_0_0_v_frmbuf_wr IS_TOP 1
    SUBMODULES {
      {MODELNAME design_1_v_frmbuf_wr_0_0_mul_14s_3ns_14_1_1 RTLNAME design_1_v_frmbuf_wr_0_0_mul_14s_3ns_14_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME design_1_v_frmbuf_wr_0_0_BYTES_PER_PIXEL_ROM_AUTO_1R RTLNAME design_1_v_frmbuf_wr_0_0_BYTES_PER_PIXEL_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME design_1_v_frmbuf_wr_0_0_MEMORY2LIVE_ROM_AUTO_1R RTLNAME design_1_v_frmbuf_wr_0_0_MEMORY2LIVE_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME design_1_v_frmbuf_wr_0_0_mm_video_m_axi RTLNAME design_1_v_frmbuf_wr_0_0_mm_video_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME design_1_v_frmbuf_wr_0_0_CTRL_s_axi RTLNAME design_1_v_frmbuf_wr_0_0_CTRL_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME design_1_v_frmbuf_wr_0_0_regslice_both RTLNAME design_1_v_frmbuf_wr_0_0_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
}
