
wire kernel_monitor_reset;
wire kernel_monitor_clock;
wire kernel_monitor_report;
assign kernel_monitor_reset = ~ap_rst_n;
assign kernel_monitor_clock = ap_clk;
assign kernel_monitor_report = 1'b0;
wire [2:0] axis_block_sigs;
wire [8:0] inst_idle_sigs;
wire [2:0] inst_block_sigs;
wire kernel_block;

assign axis_block_sigs[0] = ~grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_142.s_axis_video_TDATA_blk_n;
assign axis_block_sigs[1] = ~grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_162.s_axis_video_TDATA_blk_n;
assign axis_block_sigs[2] = ~grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_191.s_axis_video_TDATA_blk_n;

assign inst_idle_sigs[0] = grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.ap_idle;
assign inst_block_sigs[0] = (grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.ap_done & ~grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.ap_continue) | ~grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_162.img_blk_n;
assign inst_idle_sigs[1] = grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.ap_idle;
assign inst_block_sigs[1] = (grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.ap_done & ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.ap_continue) | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1380_34_fu_318.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1333_29_fu_335.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1090_24_fu_354.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_904_21_fu_373.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_863_18_fu_394.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_821_14_fu_407.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_739_11_fu_420.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_697_7_fu_432.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_605_4_fu_444.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_468.img_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1380_34_fu_318.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1333_29_fu_335.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_1090_24_fu_354.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_904_21_fu_373.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_863_18_fu_394.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_821_14_fu_407.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_739_11_fu_420.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_697_7_fu_432.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_605_4_fu_444.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_468.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_904_21_fu_373.bytePlanes_plane1_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_605_4_fu_444.bytePlanes_plane1_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_468.bytePlanes_plane1_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_605_4_fu_444.bytePlanes_plane2_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.MultiPixStream2Bytes_U0.grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_468.bytePlanes_plane2_blk_n;
assign inst_idle_sigs[2] = grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.ap_idle;
assign inst_block_sigs[2] = (grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.ap_done & ~grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.ap_continue) | ~grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1699_4_fu_267.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1652_1_fu_297.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1748_7_fu_327.bytePlanes_plane0_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1709_5_fu_277.bytePlanes_plane1_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1658_2_fu_307.bytePlanes_plane1_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1758_8_fu_337.bytePlanes_plane1_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1715_6_fu_287.bytePlanes_plane2_blk_n | ~grp_FrmbufWrHlsDataFlow_fu_176.Bytes2AXIMMvideo_U0.grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1664_3_fu_317.bytePlanes_plane2_blk_n;

assign inst_idle_sigs[3] = 1'b0;
assign inst_idle_sigs[4] = grp_FrmbufWrHlsDataFlow_fu_176.ap_idle;
assign inst_idle_sigs[5] = grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.ap_idle;
assign inst_idle_sigs[6] = grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_142.ap_idle;
assign inst_idle_sigs[7] = grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_162.ap_idle;
assign inst_idle_sigs[8] = grp_FrmbufWrHlsDataFlow_fu_176.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_191.ap_idle;

design_1_v_frmbuf_wr_0_0_hls_deadlock_idx0_monitor design_1_v_frmbuf_wr_0_0_hls_deadlock_idx0_monitor_U (
    .clock(kernel_monitor_clock),
    .reset(kernel_monitor_reset),
    .axis_block_sigs(axis_block_sigs),
    .inst_idle_sigs(inst_idle_sigs),
    .inst_block_sigs(inst_block_sigs),
    .block(kernel_block)
);


always @ (kernel_block or kernel_monitor_reset) begin
    if (kernel_block == 1'b1 && kernel_monitor_reset == 1'b0) begin
        find_kernel_block = 1'b1;
    end
    else begin
        find_kernel_block = 1'b0;
    end
end
