// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_821_14 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_dout,
        img_empty_n,
        img_read,
        img_num_data_valid,
        img_fifo_cap,
        bytePlanes_plane0_din,
        bytePlanes_plane0_full_n,
        bytePlanes_plane0_write,
        bytePlanes_plane0_num_data_valid,
        bytePlanes_plane0_fifo_cap,
        loopWidth_4,
        icmp_ln809,
        icmp_ln826_1,
        sext_ln826,
        icmp24
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input   img_empty_n;
output   img_read;
input  [2:0] img_num_data_valid;
input  [2:0] img_fifo_cap;
output  [63:0] bytePlanes_plane0_din;
input   bytePlanes_plane0_full_n;
output   bytePlanes_plane0_write;
input  [9:0] bytePlanes_plane0_num_data_valid;
input  [9:0] bytePlanes_plane0_fifo_cap;
input  [10:0] loopWidth_4;
input  [0:0] icmp_ln809;
input  [0:0] icmp_ln826_1;
input  [11:0] sext_ln826;
input  [0:0] icmp24;

reg ap_idle;
reg img_read;
reg bytePlanes_plane0_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln821_reg_297;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone_grp5_done_reg;
reg    ap_block_pp0_stage1_subdone_grp5;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] or_ln826_1_reg_318;
reg    ap_predicate_op43_read_state4;
reg    ap_block_state4_pp0_stage3_iter0_grp3;
reg    ap_block_pp0_stage3_subdone;
reg    bytePlanes_plane0_blk_n;
wire    ap_block_pp0_stage1_grp5;
reg    img_blk_n;
wire    ap_block_pp0_stage1_grp1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp2;
reg   [0:0] or_ln826_reg_314;
wire    ap_block_pp0_stage3_grp3;
wire    ap_block_pp0_stage0;
reg   [0:0] or_ln826_2_reg_322;
reg   [7:0] pix_36_reg_119;
reg   [7:0] pix_46_reg_138;
reg   [7:0] pix_45_reg_149;
reg    ap_block_pp0_stage1_11001_grp1;
reg    ap_block_pp0_stage3_11001_grp3;
reg   [0:0] icmp24_read_reg_282;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] icmp_ln826_1_read_reg_287;
reg   [0:0] icmp_ln809_read_reg_292;
wire   [0:0] icmp_ln821_fu_204_p2;
reg    ap_predicate_op51_read_state5;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln826_fu_220_p2;
reg   [0:0] icmp_ln826_reg_301;
reg   [23:0] img_read_reg_308;
wire   [0:0] or_ln826_fu_231_p2;
wire   [0:0] or_ln826_1_fu_235_p2;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire   [0:0] or_ln826_2_fu_239_p2;
reg    ap_predicate_op37_read_state3;
reg    ap_block_state3_pp0_stage2_iter0_grp2;
reg    ap_block_pp0_stage2_11001_grp2;
wire   [7:0] pix_42_fu_243_p1;
reg   [7:0] pix_42_reg_331;
wire    ap_block_pp0_stage3_11001_grp0;
reg    ap_block_pp0_stage3_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_subdone_grp0;
wire   [7:0] pix_43_fu_247_p1;
wire   [15:0] trunc_ln836_fu_251_p1;
reg   [15:0] trunc_ln836_reg_342;
wire   [7:0] pix_47_fu_254_p1;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_36_reg_119;
reg   [23:0] ap_phi_reg_pp0_iter0_phi_ln431_reg_129;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_46_reg_138;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_46_reg_138;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_45_reg_149;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_45_reg_149;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_50_reg_159;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_50_reg_159;
reg    ap_block_pp0_stage1_11001_grp5;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_49_reg_169;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_49_reg_169;
reg   [10:0] x_4_fu_72;
wire   [10:0] x_5_fu_210_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_x;
reg    ap_block_pp0_stage1_01001_grp5;
wire   [11:0] zext_ln823_fu_216_p1;
wire    ap_block_pp0_stage1_grp0;
wire    ap_block_pp0_stage3_grp0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_459;
reg    ap_condition_464;
reg    ap_condition_247;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp0_done_reg = 1'b0;
#0 x_4_fu_72 = 11'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp5)) begin
                ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp0)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        if ((1'b1 == ap_condition_464)) begin
            ap_phi_reg_pp0_iter1_pix_45_reg_149 <= pix_42_fu_243_p1;
        end else if ((1'b1 == ap_condition_459)) begin
            ap_phi_reg_pp0_iter1_pix_45_reg_149 <= pix_43_fu_247_p1;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
            ap_phi_reg_pp0_iter1_pix_45_reg_149 <= ap_phi_reg_pp0_iter0_pix_45_reg_149;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        if ((1'b1 == ap_condition_464)) begin
            ap_phi_reg_pp0_iter1_pix_46_reg_138 <= pix_36_reg_119;
        end else if ((1'b1 == ap_condition_459)) begin
            ap_phi_reg_pp0_iter1_pix_46_reg_138 <= {{img_dout[15:8]}};
        end else if (((1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
            ap_phi_reg_pp0_iter1_pix_46_reg_138 <= ap_phi_reg_pp0_iter0_pix_46_reg_138;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln821_reg_297 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln826_2_reg_322 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_pix_49_reg_169 <= ap_phi_reg_pp0_iter1_pix_45_reg_149;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln821_reg_297 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln826_2_reg_322 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_pix_49_reg_169 <= pix_47_fu_254_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter1_pix_49_reg_169 <= ap_phi_reg_pp0_iter0_pix_49_reg_169;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln821_reg_297 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln826_2_reg_322 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_pix_50_reg_159 <= ap_phi_reg_pp0_iter1_pix_46_reg_138;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln821_reg_297 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln826_2_reg_322 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_pix_50_reg_159 <= {{img_dout[15:8]}};
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter1_pix_50_reg_159 <= ap_phi_reg_pp0_iter0_pix_50_reg_159;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_247)) begin
        if (((icmp_ln821_reg_297 == 1'd0) & (or_ln826_reg_314 == 1'd1))) begin
            pix_36_reg_119 <= {{img_dout[15:8]}};
        end else if ((1'b1 == 1'b1)) begin
            pix_36_reg_119 <= ap_phi_reg_pp0_iter0_pix_36_reg_119;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln821_fu_204_p2 == 1'd0))) begin
            x_4_fu_72 <= x_5_fu_210_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_4_fu_72 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (icmp_ln821_reg_297 == 1'd0) & (or_ln826_fu_231_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (icmp_ln821_reg_297 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln826_reg_314 == 1'd1)))) begin
        ap_phi_reg_pp0_iter0_phi_ln431_reg_129 <= img_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (icmp_ln821_reg_297 == 1'd0) & (or_ln826_fu_231_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter0_pix_36_reg_119 <= {{img_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp24_read_reg_282 <= icmp24;
        icmp_ln809_read_reg_292 <= icmp_ln809;
        icmp_ln826_1_read_reg_287 <= icmp_ln826_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln821_reg_297 <= icmp_ln821_fu_204_p2;
        icmp_ln826_reg_301 <= icmp_ln826_fu_220_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_read_reg_308 <= img_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_ln826_1_reg_318 <= or_ln826_1_fu_235_p2;
        or_ln826_2_reg_322 <= or_ln826_2_fu_239_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_ln826_reg_314 <= or_ln826_fu_231_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        pix_42_reg_331 <= pix_42_fu_243_p1;
        trunc_ln836_reg_342 <= trunc_ln836_fu_251_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_45_reg_149 <= ap_phi_reg_pp0_iter1_pix_45_reg_149;
        pix_46_reg_138 <= ap_phi_reg_pp0_iter1_pix_46_reg_138;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln821_reg_297 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x = 11'd0;
    end else begin
        ap_sig_allocacmp_x = x_4_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg) & (1'b0 == ap_block_pp0_stage1_grp5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane0_blk_n = bytePlanes_plane0_full_n;
    end else begin
        bytePlanes_plane0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane0_write = 1'b1;
    end else begin
        bytePlanes_plane0_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op43_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp3) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_grp1) & (icmp_ln821_reg_297 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp2) & (icmp_ln821_reg_297 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln826_reg_314 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln821_reg_297 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln826_2_reg_322 == 1'd1)))) begin
        img_blk_n = img_empty_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op43_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (icmp_ln821_reg_297 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_predicate_op37_read_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op51_read_state5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_read = 1'b1;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001_grp5 = ((1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg) & (bytePlanes_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp5 = ((1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg) & (bytePlanes_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg) & (bytePlanes_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp5 = ((1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg) & (bytePlanes_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp2));
end

assign ap_block_pp0_stage3_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

assign ap_block_pp0_stage3_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp3));
end

assign ap_block_pp0_stage3_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((icmp_ln821_reg_297 == 1'd0) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp2 = ((img_empty_n == 1'b0) & (ap_predicate_op37_read_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0_grp3 = ((ap_predicate_op43_read_state4 == 1'b1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = ((img_empty_n == 1'b0) & (ap_predicate_op51_read_state5 == 1'b1));
end

always @ (*) begin
    ap_condition_247 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_459 = ((or_ln826_1_reg_318 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (icmp_ln821_reg_297 == 1'd0));
end

always @ (*) begin
    ap_condition_464 = ((or_ln826_1_reg_318 == 1'd0) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (icmp_ln821_reg_297 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter0_pix_45_reg_149 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_46_reg_138 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_49_reg_169 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_50_reg_159 = 'bx;

always @ (*) begin
    ap_predicate_op37_read_state3 = ((icmp_ln821_reg_297 == 1'd0) & (or_ln826_reg_314 == 1'd1));
end

always @ (*) begin
    ap_predicate_op43_read_state4 = ((or_ln826_1_reg_318 == 1'd1) & (icmp_ln821_reg_297 == 1'd0));
end

always @ (*) begin
    ap_predicate_op51_read_state5 = ((icmp_ln821_reg_297 == 1'd0) & (or_ln826_2_reg_322 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign bytePlanes_plane0_din = {{{{{{{ap_phi_reg_pp0_iter1_pix_50_reg_159}, {ap_phi_reg_pp0_iter1_pix_49_reg_169}}, {pix_46_reg_138}}, {pix_45_reg_149}}, {pix_36_reg_119}}, {pix_42_reg_331}}, {trunc_ln836_reg_342}};

assign icmp_ln821_fu_204_p2 = ((ap_sig_allocacmp_x == loopWidth_4) ? 1'b1 : 1'b0);

assign icmp_ln826_fu_220_p2 = (($signed(zext_ln823_fu_216_p1) < $signed(sext_ln826)) ? 1'b1 : 1'b0);

assign or_ln826_1_fu_235_p2 = (icmp_ln826_reg_301 | icmp_ln826_1_read_reg_287);

assign or_ln826_2_fu_239_p2 = (icmp_ln826_reg_301 | icmp_ln809_read_reg_292);

assign or_ln826_fu_231_p2 = (icmp_ln826_reg_301 | icmp24_read_reg_282);

assign pix_42_fu_243_p1 = ap_phi_reg_pp0_iter0_phi_ln431_reg_129[7:0];

assign pix_43_fu_247_p1 = img_dout[7:0];

assign pix_47_fu_254_p1 = img_dout[7:0];

assign trunc_ln836_fu_251_p1 = img_read_reg_308[15:0];

assign x_5_fu_210_p2 = (ap_sig_allocacmp_x + 11'd1);

assign zext_ln823_fu_216_p1 = ap_sig_allocacmp_x;

endmodule //design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_821_14
