set SynModuleInfo {
  {SRCNAME {reg<unsigned short>1} MODELNAME reg_unsigned_short_1 RTLNAME top_design_v_mix_0_0_reg_unsigned_short_1}
  {SRCNAME AXIvideo2MultiPixStream.1_Pipeline_loop_wait_for_start MODELNAME AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start RTLNAME top_design_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start
    SUBMODULES {
      {MODELNAME top_design_v_mix_0_0_flow_control_loop_pipe_sequential_init RTLNAME top_design_v_mix_0_0_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME top_design_v_mix_0_0_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME AXIvideo2MultiPixStream.1_Pipeline_loop_width MODELNAME AXIvideo2MultiPixStream_1_Pipeline_loop_width RTLNAME top_design_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_width}
  {SRCNAME AXIvideo2MultiPixStream.1_Pipeline_loop_wait_for_eol MODELNAME AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol RTLNAME top_design_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol}
  {SRCNAME AXIvideo2MultiPixStream.1 MODELNAME AXIvideo2MultiPixStream_1 RTLNAME top_design_v_mix_0_0_AXIvideo2MultiPixStream_1}
  {SRCNAME v_mix_420_to_422<false>.2_Pipeline_VITIS_LOOP_76_2 MODELNAME v_mix_420_to_422_false_2_Pipeline_VITIS_LOOP_76_2 RTLNAME top_design_v_mix_0_0_v_mix_420_to_422_false_2_Pipeline_VITIS_LOOP_76_2}
  {SRCNAME v_mix_420_to_422<false>.2 MODELNAME v_mix_420_to_422_false_2 RTLNAME top_design_v_mix_0_0_v_mix_420_to_422_false_2}
  {SRCNAME v_mix_422_to_444<false>.3_Pipeline_VITIS_LOOP_105_2 MODELNAME v_mix_422_to_444_false_3_Pipeline_VITIS_LOOP_105_2 RTLNAME top_design_v_mix_0_0_v_mix_422_to_444_false_3_Pipeline_VITIS_LOOP_105_2}
  {SRCNAME v_mix_422_to_444<false>.3 MODELNAME v_mix_422_to_444_false_3 RTLNAME top_design_v_mix_0_0_v_mix_422_to_444_false_3}
  {SRCNAME v_mix_yuv2rgb<false>.4_Pipeline_VITIS_LOOP_897_2 MODELNAME v_mix_yuv2rgb_false_4_Pipeline_VITIS_LOOP_897_2 RTLNAME top_design_v_mix_0_0_v_mix_yuv2rgb_false_4_Pipeline_VITIS_LOOP_897_2}
  {SRCNAME v_mix_yuv2rgb<false>.4 MODELNAME v_mix_yuv2rgb_false_4 RTLNAME top_design_v_mix_0_0_v_mix_yuv2rgb_false_4}
  {SRCNAME {reg<unsigned short>} MODELNAME reg_unsigned_short_s RTLNAME top_design_v_mix_0_0_reg_unsigned_short_s}
  {SRCNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start MODELNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start RTLNAME top_design_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start}
  {SRCNAME AXIvideo2MultiPixStream_Pipeline_loop_width MODELNAME AXIvideo2MultiPixStream_Pipeline_loop_width RTLNAME top_design_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width}
  {SRCNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol MODELNAME AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol RTLNAME top_design_v_mix_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol}
  {SRCNAME AXIvideo2MultiPixStream MODELNAME AXIvideo2MultiPixStream RTLNAME top_design_v_mix_0_0_AXIvideo2MultiPixStream}
  {SRCNAME v_mix_420_to_422<false>_Pipeline_VITIS_LOOP_76_2 MODELNAME v_mix_420_to_422_false_Pipeline_VITIS_LOOP_76_2 RTLNAME top_design_v_mix_0_0_v_mix_420_to_422_false_Pipeline_VITIS_LOOP_76_2}
  {SRCNAME v_mix_420_to_422<false> MODELNAME v_mix_420_to_422_false_s RTLNAME top_design_v_mix_0_0_v_mix_420_to_422_false_s}
  {SRCNAME v_mix_422_to_444<false>_Pipeline_VITIS_LOOP_105_2 MODELNAME v_mix_422_to_444_false_Pipeline_VITIS_LOOP_105_2 RTLNAME top_design_v_mix_0_0_v_mix_422_to_444_false_Pipeline_VITIS_LOOP_105_2}
  {SRCNAME v_mix_422_to_444<false> MODELNAME v_mix_422_to_444_false_s RTLNAME top_design_v_mix_0_0_v_mix_422_to_444_false_s}
  {SRCNAME v_mix_yuv2rgb<false>_Pipeline_VITIS_LOOP_897_2 MODELNAME v_mix_yuv2rgb_false_Pipeline_VITIS_LOOP_897_2 RTLNAME top_design_v_mix_0_0_v_mix_yuv2rgb_false_Pipeline_VITIS_LOOP_897_2}
  {SRCNAME v_mix_yuv2rgb<false> MODELNAME v_mix_yuv2rgb_false_s RTLNAME top_design_v_mix_0_0_v_mix_yuv2rgb_false_s}
  {SRCNAME v_mix_upsample<false>_Pipeline_VITIS_LOOP_107_2 MODELNAME v_mix_upsample_false_Pipeline_VITIS_LOOP_107_2 RTLNAME top_design_v_mix_0_0_v_mix_upsample_false_Pipeline_VITIS_LOOP_107_2}
  {SRCNAME v_mix_upsample<false> MODELNAME v_mix_upsample_false_s RTLNAME top_design_v_mix_0_0_v_mix_upsample_false_s}
  {SRCNAME {reg<unsigned short>7} MODELNAME reg_unsigned_short_7 RTLNAME top_design_v_mix_0_0_reg_unsigned_short_7}
  {SRCNAME {v_mix_core_alpha<true, false>_Pipeline_VITIS_LOOP_395_3} MODELNAME v_mix_core_alpha_true_false_Pipeline_VITIS_LOOP_395_3 RTLNAME top_design_v_mix_0_0_v_mix_core_alpha_true_false_Pipeline_VITIS_LOOP_395_3
    SUBMODULES {
      {MODELNAME top_design_v_mix_0_0_mac_muladd_9s_9ns_16s_16_4_1 RTLNAME top_design_v_mix_0_0_mac_muladd_9s_9ns_16s_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
      {MODELNAME top_design_v_mix_0_0_mac_muladd_9ns_9s_16s_16_4_1 RTLNAME top_design_v_mix_0_0_mac_muladd_9ns_9s_16s_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME {v_mix_core_alpha<true, false>} MODELNAME v_mix_core_alpha_true_false_s RTLNAME top_design_v_mix_0_0_v_mix_core_alpha_true_false_s}
  {SRCNAME v_mix_rgb2yuv<false>_Pipeline_VITIS_LOOP_1042_2 MODELNAME v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2 RTLNAME top_design_v_mix_0_0_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2}
  {SRCNAME v_mix_rgb2yuv<false> MODELNAME v_mix_rgb2yuv_false_s RTLNAME top_design_v_mix_0_0_v_mix_rgb2yuv_false_s}
  {SRCNAME v_mix_444_to_422<false>_Pipeline_VITIS_LOOP_718_2 MODELNAME v_mix_444_to_422_false_Pipeline_VITIS_LOOP_718_2 RTLNAME top_design_v_mix_0_0_v_mix_444_to_422_false_Pipeline_VITIS_LOOP_718_2}
  {SRCNAME v_mix_444_to_422<false> MODELNAME v_mix_444_to_422_false_s RTLNAME top_design_v_mix_0_0_v_mix_444_to_422_false_s}
  {SRCNAME v_mix_422_to_420<false>_Pipeline_VITIS_LOOP_508_2 MODELNAME v_mix_422_to_420_false_Pipeline_VITIS_LOOP_508_2 RTLNAME top_design_v_mix_0_0_v_mix_422_to_420_false_Pipeline_VITIS_LOOP_508_2}
  {SRCNAME v_mix_422_to_420<false> MODELNAME v_mix_422_to_420_false_s RTLNAME top_design_v_mix_0_0_v_mix_422_to_420_false_s}
  {SRCNAME MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3903_3 MODELNAME MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3903_3 RTLNAME top_design_v_mix_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3903_3}
  {SRCNAME MultiPixStream2AXIvideo MODELNAME MultiPixStream2AXIvideo RTLNAME top_design_v_mix_0_0_MultiPixStream2AXIvideo}
  {SRCNAME VMixHlsDataFlowFunction MODELNAME VMixHlsDataFlowFunction RTLNAME top_design_v_mix_0_0_VMixHlsDataFlowFunction
    SUBMODULES {
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME srcLayer0_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME srcLayer0Yuv422_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME srcLayer0Yuv_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME outLayer0_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME srcLayer1_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME srcLayer1Yuv422_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME srcLayer1Yuv_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME srcLayer1Rgb_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME srcLayer1x_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME outLayer1_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME outYuv_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME out422_U}
      {MODELNAME top_design_v_mix_0_0_fifo_w24_d2_S RTLNAME top_design_v_mix_0_0_fifo_w24_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME out420_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_420_to_422_false_2_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_420_to_422_false_2_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_420_to_422_false_2_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_422_to_444_false_3_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_422_to_444_false_3_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_422_to_444_false_3_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_yuv2rgb_false_4_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_yuv2rgb_false_4_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_yuv2rgb_false_4_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_core_alpha_true_false_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_core_alpha_true_false_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_core_alpha_true_false_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_420_to_422_false_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_420_to_422_false_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_420_to_422_false_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_422_to_444_false_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_422_to_444_false_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_422_to_444_false_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_yuv2rgb_false_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_yuv2rgb_false_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_yuv2rgb_false_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_upsample_false_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_upsample_false_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_upsample_false_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_rgb2yuv_false_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_rgb2yuv_false_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_rgb2yuv_false_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_444_to_422_false_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_444_to_422_false_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_444_to_422_false_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_v_mix_422_to_420_false_U0 RTLNAME top_design_v_mix_0_0_start_for_v_mix_422_to_420_false_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_v_mix_422_to_420_false_U0_U}
      {MODELNAME top_design_v_mix_0_0_start_for_MultiPixStream2AXIvideo_U0 RTLNAME top_design_v_mix_0_0_start_for_MultiPixStream2AXIvideo_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_MultiPixStream2AXIvideo_U0_U}
    }
  }
  {SRCNAME v_mix MODELNAME v_mix RTLNAME top_design_v_mix_0_0_v_mix IS_TOP 1
    SUBMODULES {
      {MODELNAME top_design_v_mix_0_0_bitselect_1ns_32ns_1ns_1_1_1 RTLNAME top_design_v_mix_0_0_bitselect_1ns_32ns_1ns_1_1_1 BINDTYPE op TYPE bitselect IMPL auto}
      {MODELNAME top_design_v_mix_0_0_CTRL_s_axi RTLNAME top_design_v_mix_0_0_CTRL_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME top_design_v_mix_0_0_regslice_both RTLNAME top_design_v_mix_0_0_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
}
