domain_path: C:\Users\Sergey\Documents\Xilinx\z7000_hdmi\HDMI_VDMA\Vitis_VDMA_SA\platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: /tools/xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
