set_property SRC_FILE_INFO {cfile:/home/serg/Documents/Xilinx/z700_hdmi/HDMI_VDMA/HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/smartconnect.xdc rfile:../../../HDMI_VDMA.gen/sources_1/bd/top_design/ip/top_design_smartconnect_0_0/smartconnect.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-11 -user "smartconnect" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -hier -filter {NAME =~ */clk_map/psr*/*/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX/*syncstages_ff_reg*/D}]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -user "smartconnect" -desc "Timing uncritical paths" -tags "1165895" -scope -internal -to [get_pins -quiet -filter {REF_PIN_NAME=~*D || REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ */s*_entry_pipeline/s*_si_converter/inst/gen_axilite_conv.axilite_conv_inst/*_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-1} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -to [get_pins -quiet -filter {REF_PIN_NAME=~*D || REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-1} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-2} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -to [get_pins -quiet -filter {REF_PIN_NAME=~*D || REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-2} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-4} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -to [get_pins -quiet -filter {REF_PIN_NAME=~*D || REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-4} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-10} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -to [get_pins -quiet -filter {REF_PIN_NAME=~*D || REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-10} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -to [get_pins -quiet -filter {REF_PIN_NAME=~*D || REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-13} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -to [get_pins -quiet -filter {REF_PIN_NAME=~*D || REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
set_property src_info {type:SCOPED_XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-13} -user "smartconnect" -desc "Waiver CDC path" -tags "1165895" -scope -internal -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ */*_node/inst/inst_mi_handler/*}]]
