
wire kernel_monitor_reset;
wire kernel_monitor_clock;
wire kernel_monitor_report;
assign kernel_monitor_reset = ~ap_rst_n;
assign kernel_monitor_clock = ap_clk;
assign kernel_monitor_report = 1'b0;
wire [6:0] axis_block_sigs;
wire [25:0] inst_idle_sigs;
wire [13:0] inst_block_sigs;
wire kernel_block;

assign axis_block_sigs[0] = ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_142.s_axis_video_TDATA_blk_n;
assign axis_block_sigs[1] = ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_162.s_axis_video_TDATA_blk_n;
assign axis_block_sigs[2] = ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_190.s_axis_video_TDATA_blk_n;
assign axis_block_sigs[3] = ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140.s_axis_video1_TDATA_blk_n;
assign axis_block_sigs[4] = ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160.s_axis_video1_TDATA_blk_n;
assign axis_block_sigs[5] = ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188.s_axis_video1_TDATA_blk_n;
assign axis_block_sigs[6] = ~grp_VMixHlsDataFlowFunction_fu_391.MultiPixStream2AXIvideo_U0.grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3903_3_fu_96.m_axis_video_TDATA_blk_n;

assign inst_idle_sigs[0] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.ap_idle;
assign inst_block_sigs[0] = (grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_162.srcLayer0_blk_n;
assign inst_idle_sigs[1] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_2_U0.ap_idle;
assign inst_block_sigs[1] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_2_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_2_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_2_U0.grp_v_mix_420_to_422_false_2_Pipeline_VITIS_LOOP_76_2_fu_74.srcLayer0_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_2_U0.grp_v_mix_420_to_422_false_2_Pipeline_VITIS_LOOP_76_2_fu_74.srcLayer0Yuv422_blk_n;
assign inst_idle_sigs[2] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_3_U0.ap_idle;
assign inst_block_sigs[2] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_3_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_3_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_3_U0.grp_v_mix_422_to_444_false_3_Pipeline_VITIS_LOOP_105_2_fu_74.srcLayer0Yuv422_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_3_U0.grp_v_mix_422_to_444_false_3_Pipeline_VITIS_LOOP_105_2_fu_74.srcLayer0Yuv_blk_n;
assign inst_idle_sigs[3] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_4_U0.ap_idle;
assign inst_block_sigs[3] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_4_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_4_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_4_U0.grp_v_mix_yuv2rgb_false_4_Pipeline_VITIS_LOOP_897_2_fu_74.srcLayer0Yuv_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_4_U0.grp_v_mix_yuv2rgb_false_4_Pipeline_VITIS_LOOP_897_2_fu_74.outLayer0_blk_n;
assign inst_idle_sigs[4] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.ap_idle;
assign inst_block_sigs[4] = (grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160.srcLayer1_blk_n;
assign inst_idle_sigs[5] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_U0.ap_idle;
assign inst_block_sigs[5] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_U0.grp_v_mix_420_to_422_false_Pipeline_VITIS_LOOP_76_2_fu_70.srcLayer1_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_420_to_422_false_U0.grp_v_mix_420_to_422_false_Pipeline_VITIS_LOOP_76_2_fu_70.srcLayer1Yuv422_blk_n;
assign inst_idle_sigs[6] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_U0.ap_idle;
assign inst_block_sigs[6] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_U0.grp_v_mix_422_to_444_false_Pipeline_VITIS_LOOP_105_2_fu_70.srcLayer1Yuv422_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_444_false_U0.grp_v_mix_422_to_444_false_Pipeline_VITIS_LOOP_105_2_fu_70.srcLayer1Yuv_blk_n;
assign inst_idle_sigs[7] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_U0.ap_idle;
assign inst_block_sigs[7] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_U0.grp_v_mix_yuv2rgb_false_Pipeline_VITIS_LOOP_897_2_fu_70.srcLayer1Yuv_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_yuv2rgb_false_U0.grp_v_mix_yuv2rgb_false_Pipeline_VITIS_LOOP_897_2_fu_70.srcLayer1Rgb_blk_n;
assign inst_idle_sigs[8] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_upsample_false_U0.ap_idle;
assign inst_block_sigs[8] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_upsample_false_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_upsample_false_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_upsample_false_U0.grp_v_mix_upsample_false_Pipeline_VITIS_LOOP_107_2_fu_70.srcLayer1Rgb_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_upsample_false_U0.grp_v_mix_upsample_false_Pipeline_VITIS_LOOP_107_2_fu_70.srcLayer1x_blk_n;
assign inst_idle_sigs[9] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_core_alpha_true_false_U0.ap_idle;
assign inst_block_sigs[9] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_core_alpha_true_false_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_core_alpha_true_false_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_core_alpha_true_false_U0.grp_v_mix_core_alpha_true_false_Pipeline_VITIS_LOOP_395_3_fu_170.outLayer0_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_core_alpha_true_false_U0.grp_v_mix_core_alpha_true_false_Pipeline_VITIS_LOOP_395_3_fu_170.srcLayer1x_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_core_alpha_true_false_U0.grp_v_mix_core_alpha_true_false_Pipeline_VITIS_LOOP_395_3_fu_170.outLayer1_blk_n;
assign inst_idle_sigs[10] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_rgb2yuv_false_U0.ap_idle;
assign inst_block_sigs[10] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_rgb2yuv_false_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_rgb2yuv_false_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_rgb2yuv_false_U0.grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62.outLayer1_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_rgb2yuv_false_U0.grp_v_mix_rgb2yuv_false_Pipeline_VITIS_LOOP_1042_2_fu_62.outYuv_blk_n;
assign inst_idle_sigs[11] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_444_to_422_false_U0.ap_idle;
assign inst_block_sigs[11] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_444_to_422_false_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_444_to_422_false_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_444_to_422_false_U0.grp_v_mix_444_to_422_false_Pipeline_VITIS_LOOP_718_2_fu_62.outYuv_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_444_to_422_false_U0.grp_v_mix_444_to_422_false_Pipeline_VITIS_LOOP_718_2_fu_62.out422_blk_n;
assign inst_idle_sigs[12] = grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_420_false_U0.ap_idle;
assign inst_block_sigs[12] = (grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_420_false_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_420_false_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_420_false_U0.grp_v_mix_422_to_420_false_Pipeline_VITIS_LOOP_508_2_fu_62.out422_blk_n | ~grp_VMixHlsDataFlowFunction_fu_391.v_mix_422_to_420_false_U0.grp_v_mix_422_to_420_false_Pipeline_VITIS_LOOP_508_2_fu_62.out420_blk_n;
assign inst_idle_sigs[13] = grp_VMixHlsDataFlowFunction_fu_391.MultiPixStream2AXIvideo_U0.ap_idle;
assign inst_block_sigs[13] = (grp_VMixHlsDataFlowFunction_fu_391.MultiPixStream2AXIvideo_U0.ap_done & ~grp_VMixHlsDataFlowFunction_fu_391.MultiPixStream2AXIvideo_U0.ap_continue) | ~grp_VMixHlsDataFlowFunction_fu_391.MultiPixStream2AXIvideo_U0.grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3903_3_fu_96.out420_blk_n;

assign inst_idle_sigs[14] = 1'b0;
assign inst_idle_sigs[15] = grp_VMixHlsDataFlowFunction_fu_391.ap_idle;
assign inst_idle_sigs[16] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.ap_idle;
assign inst_idle_sigs[17] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_142.ap_idle;
assign inst_idle_sigs[18] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_162.ap_idle;
assign inst_idle_sigs[19] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_1_U0.grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_190.ap_idle;
assign inst_idle_sigs[20] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.ap_idle;
assign inst_idle_sigs[21] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_140.ap_idle;
assign inst_idle_sigs[22] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_160.ap_idle;
assign inst_idle_sigs[23] = grp_VMixHlsDataFlowFunction_fu_391.AXIvideo2MultiPixStream_U0.grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_188.ap_idle;
assign inst_idle_sigs[24] = grp_VMixHlsDataFlowFunction_fu_391.MultiPixStream2AXIvideo_U0.ap_idle;
assign inst_idle_sigs[25] = grp_VMixHlsDataFlowFunction_fu_391.MultiPixStream2AXIvideo_U0.grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3903_3_fu_96.ap_idle;

top_design_v_mix_0_0_hls_deadlock_idx0_monitor top_design_v_mix_0_0_hls_deadlock_idx0_monitor_U (
    .clock(kernel_monitor_clock),
    .reset(kernel_monitor_reset),
    .axis_block_sigs(axis_block_sigs),
    .inst_idle_sigs(inst_idle_sigs),
    .inst_block_sigs(inst_block_sigs),
    .block(kernel_block)
);


always @ (kernel_block or kernel_monitor_reset) begin
    if (kernel_block == 1'b1 && kernel_monitor_reset == 1'b0) begin
        find_kernel_block = 1'b1;
    end
    else begin
        find_kernel_block = 1'b0;
    end
end
